### ISSUE TITLE
Default replication is async, not sync, and cannot be forced to be sync

### ISSUE THREAD

**Issue by rmpinchback** [bitnami/bitnami-docker-postgresql-repmgr#100]
I believe the same replication behavior is intended for this docker image as is documented for the bitnami/postgresql image.  Replication being synchronous should be 'on' by default.  The postgresql.conf file does appear to set `POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on`, however when querying pg_stat_replication the sync state says 'async'.  Manually supplying `POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on` does nothing, I believe because the corresponding variable in postgresql.conf (`synchronous_commit`) is commented out but says the default is `on` anyways.

**Steps to reproduce the issue:**

1. Create a docker-compose.yml based on the image: postgresql-repmgr:14.1.0 (attached below)
2. Follow the instructions for a 2-node setup as documented on Docker Hub
3. Add to the environment variables: POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
4. docker-compose up
5. Bring up a temp container to run psql against pg-0
6. select application_name as server,state,sync_priority as priority,sync_state from pg_stat_replication;
7. eyeball the results of the query, and eyeball postgresql.conf in the conf directory of the volume to see the mismatch.

**Describe the results you received:**

```
postgres=# select application_name as server,state,sync_priority as priority,sync_state from pg_stat_replication;
 server |   state   | priority | sync_state
--------+-----------+----------+------------
 pg-1   | streaming |        0 | async
(1 row)
```

and the relevant lines from postgresql.conf:

```
#synchronous_commit = on		# synchronization level;
					# off, local, remote_write, remote_apply, or on
```

**Describe the results you expected:**

Well aside from the sync status saying 'sync' I believe the gap is in the setup of the postgresql.conf, the following section needs to be populated to know about `pg-1`:

```
#synchronous_standby_names = ''	# standby servers that provide sync rep
				# method to choose sync standbys, number of sync standbys,
				# and comma-separated list of application_name
				# from standby(s); '*' = all
```

I'm truly not sure why this isn't being populated.  I didn't override the POSTGRESQL_CLUSTER_APP_NAME, which (while not mentioned in the bitnami/postgresql documentation) appears to be the other required parameter.  It should be defaulting to walreceiver in `/14/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh`, and then `/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh` should be fixing up synchronous_standby_names within `postgresql_configure_synchronous_replication()` but that clearly isn't happening.  I checked the postgresql.conf files for both nodes (pg-0 and pg-1) , both were the same for that variable.

**Additional information you deem important (e.g. issue happens only occasionally):**

Appears 100% consistent.  I've wiped the volumes, tried again, makes no difference.

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.768GiB
 Name: docker-desktop
 ID: QZW2:BJIM:WW4U:D666:K54F:DFFX:GITS:4GYN:CJMP:Q3VR:SJFH:R6ET
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Image tag: postgresql-repmgr:14.1.0

With a few value tweaks for privacy/security, below is the docker-compose.yml.  And yes, I'm pretty sure the YAML aliasing works correctly although unwinding it is just copy-paste-fuss-around to replicate the common boilerplate; you could use `https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/docker-compose.yml` instead if you prefer, that's actually what I started from and then tweaked the env variables and volumes.

```
version: "3.9"

# -----------------------------------------------------------
# client access
# -----------------------------------------------------------

# to run psql connected to primary:
#   docker run -it --rm --network my-net bitnami/postgresql-repmgr:14.1.0 psql -h pg-0 -U postgres

# to inspect replication:
#   select application_name as server,state,sync_priority as priority,sync_state from pg_stat_replication;

# -----------------------------------------------------------
# aliases
# -----------------------------------------------------------

# common parts of a postgres container
x-pg: &default-pg
  image: bitnami/postgresql-repmgr:14.1.0
  restart: always
  networks:
    - my-net

# common parts of the postgres environment
x-pg-postgres-pw: &pg-postgres-pw POSTGRESQL_POSTGRES_PASSWORD=foobarpw
x-pg-user: &pg-user POSTGRESQL_USERNAME=foobar
x-pg-pw: &pg-pw POSTGRESQL_PASSWORD=foobar
x-pg-db: &pg-db POSTGRESQL_DATABASE=foobar
x-pg-sync-mode: &pg-sync-mode POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
x-pg-sync-repls: &pg-sync-repls POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
x-pg-rep-pw: &pg-rep-pw REPMGR_PASSWORD=foobarrepmgrpw
x-pg-rep-phost: &pg-rep-phost REPMGR_PRIMARY_HOST=pg-0
x-pg-rep-pport: &pg-rep-pport REPMGR_PRIMARY_PORT=5432
x-pg-rep-nodes: &pg-rep-nodes REPMGR_PARTNER_NODES=pg-0,pg-1:5432
x-pg-rep-port: &pg-rep-port REPMGR_PORT_NUMBER=5432

# -----------------------------------------------------------

networks:
  my-net:
    name: my-net
    driver: bridge

services:

  pg-0:
    <<: *default-pg
    container_name: pg-0
    volumes:
      - ./data/pg_0:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - *pg-postgres-pw
      - *pg-user
      - *pg-pw
      - *pg-db
      - *pg-sync-mode
      - *pg-sync-repls
      - *pg-rep-pw
      - *pg-rep-phost
      - *pg-rep-pport
      - *pg-rep-nodes
      - *pg-rep-port
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0

  pg-1:
    <<: *default-pg
    container_name: pg-1
    volumes:
      - ./data/pg_1:/bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      - *pg-postgres-pw
      - *pg-user
      - *pg-pw
      - *pg-db
      - *pg-sync-mode
      - *pg-sync-repls
      - *pg-rep-pw
      - *pg-rep-phost
      - *pg-rep-pport
      - *pg-rep-nodes
      - *pg-rep-port
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
```

**Comment by juan131** [comment]
Hi @rmpinchback 

I have confirmed with @rafariossaa that this topic has been discussed in the past, and there were users that supported to enable the synchronous commit mode by default, while others defended the different opinion.

In any case, regardless what default value we set, I guess the problem here is that you're unable to customize, am i right? The _POSTGRESQL_SYNCHRONOUS_COMMIT_MODE_  env. var is declared/defined at [postgresql-env.sh](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/14/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh#L248 ), and it's used in the [`postgresql_configure_synchronous_replication `](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L390) function. Isn't it working as expected?

**Comment by rmpinchback** [comment]
Correct, it is not working as expected. I can go in and do manual surgery
on postgresql.conf to make something happen, that wasn't my point. I just
wanted to report that your additional scripting for the image did not
currently behave as I think was intended. The replication is working
because the read replica node reaches out to the primary, not because the
primary config knew about the replica in the first place, which is what I
believe is required for sync mode.  The code was written to do that, but
the resulting files aren't showing evidence of that code succeeding.

**Comment by rmpinchback** [comment]
If you look at the bash function I mentioned, and the postgresql.conf
fragment it should have altered (included in the issue), you should be able
to see what I mean.

**Comment by juan131** [comment]
Thanks @rmpinchback !! You're right, I was able to reproduce it...

I've created an internal task to investigate what's failing in our libraries and added it to our backlog. In any case, feel free to contribute with a PR if you find out the root of the issue.

Thanks again for reporting it.

**Comment by carrodher** [comment]
Hi, this issue should be solved in the recent container images version. The Helm chart was updated as well, can you give a try? Please, feel free to reopen this ticket if something doesn't work as expected.
