### ISSUE TITLE
How to compile the postgresql-rempgr package?

### ISSUE THREAD

**Issue by tosone** [bitnami/bitnami-docker-postgresql-repmgr#101]
**Description**

I know that build the Dockerfile will download file from https://downloads.bitnami.com/files/stacksmith/postgresql-repmgr-12.9.0-0-linux-amd64-debian-10.tar.gz, and how can I build this package by myself?

**Comment by Mauraza** [comment]
Hi @tosone,

That tarball you can uncompress them you will see that is only the postgresql-repmgr official files plus some metadata. If you build the container image on your side, those packages are downloaded and bundled into the image.
