### ISSUE TITLE
Could not fork new process for connection: Resource temporarily unavailable

### ISSUE THREAD

**Issue by elotrofausto** [bitnami/bitnami-docker-postgresql-repmgr#102]
**Description**

Container stops working after several days running (12-18 days). Restarting the container doesn't solve the issue and we need to rebuild it.

"could not fork new process for connection: Resource temporarily unavailable\n"

**Steps to reproduce the issue:**

1. Run two postgresql-repmgr containers in different servers (Debian 10) and replication mode.
2. Containers run without issues for about 12-18 days.
3. Then we get the following error on the master node:

"could not fork new process for connection: Resource temporarily unavailable"

**Describe the results you expected:**

I expect the containers to run without issues in production.

**Additional information you deem important (e.g. issue happens only occasionally):**

This happened two or three times and always after a couple of weeks running or so.
Restarting the container doesn't help and we need to rebuild it. We are using docker-compose and bitnami-docker-postgresql-repmgr is 1 out of 12 containers. It's the only one that fails.

We think this may be a File Descriptor issue. Could it be that running the container as non-root caused the issue? We tried running the container as root but it's not possible either, as per the open issue described in: https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/72

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.8
  GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113ee
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 198
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc version: v1.0.0-0-g84113ee
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-17-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.67GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Both sides running on VMWare Debian 10 VMs.

**Comment by alemorcuq** [comment]
[This](https://postgrespro.com/list/id/A737B7A37273E048B164557ADEF4A58B50F6FACF@ntex2010a.host.magwien.gv.at) suggests the issue might be related to file descriptors. Did you try increasing the max file descriptors with `fs.file-max`? Out of curiosity, how would running the container as root help with this?

**Comment by elotrofausto** [comment]
> [This](https://postgrespro.com/list/id/A737B7A37273E048B164557ADEF4A58B50F6FACF@ntex2010a.host.magwien.gv.at) suggests the issue might be related to file descriptors. Did you try increasing the max file descriptors with `fs.file-max`? Out of curiosity, how would running the container as root help with this?

Hello @alemorcuq

Thanks for the response. Isn't it discouraged to increase the file descriptors from a security perspective? Did you experience this issue before? What would it be a reasonable level?

Regarding the root containers, we thought the issue could be related to file descriptors set at a user level, and the unprivileged user 1001 having more restrictions than the root user.

**Comment by miguelaeh** [comment]
Hi @elotrofausto ,

> Isn't it discouraged to increase the file descriptors from a security perspective? 
Could you elaborate on this?
