### ISSUE TITLE
no arm64 images of containers

### ISSUE THREAD

**Issue by piwi3910** [bitnami/bitnami-docker-postgresql-repmgr#104]
Please add to your build pipeline support for arm64

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
