### ISSUE TITLE
Document a process for upgrading an existing Postgresql data directory to use postgresql-repmgr

### ISSUE THREAD

**Issue by bergner** [bitnami/bitnami-docker-postgresql-repmgr#108]
**Description**

The postgresql-repmgr image is fundamentally designed to start from an empty data directory and bootstrapping of repmgr only happens when the data dir is empty. I think it would be a good idea to explicitly document a procedure for how a user can take an existing Postgresql database (e.g. one that used the standard https://hub.docker.com/_/postgres image) and upgrade it to use postgresql-repmgr.

**Steps to reproduce the issue:**

1. Bootstrap a database with the standard https://hub.docker.com/_/postgres image using a docker volume to hold the data.
2. Attempt to use postgresql-repmgr on the same data directory to try to add redundancy to a previously existing setup.
3. Database doesn't work at all because repmgr was not initialized. This is also the case after doing chmod -R 1001 on the data volume to compensate for the fact that postgres and postgresql-repmgr uses different UIDs.

**Suggestion**

Provide instructions and/or scripts that utilize pg_dump and pg_restore to save a snapshot of the original database and restore it into an empty bootstrapped postgresql-repmgr database. Something along the lines of this:

On the existing database save a database dump and save it on persistent storage on the host. Note that environment variables used here are based on the standard postgres image.

```
container=$(docker ps -q --filter name=postgres)
docker exec "$container" bash -c 'env PGPASSWORD=${PGPASSWORD:-${POSTGRES_PASSWORD}} pg_dump -Fc -U $POSTGRES_USER -d $POSTGRES_DB -f /tmp/db.dump'
docker cp "$container:/tmp/db.dump" db.dump
docker exec "$container" rm -f /tmp/db.dump
```

Start a fresh instance of postgresql-repmgr with an empty data volume, then restore the dump:

```
container=$(docker ps -q --filter name=postgresql-repmgr)
docker cp db.dump "$container:/tmp/db.dump"
docker exec "$container" bash -c 'env PGPASSWORD=${PGPASSWORD:-${POSTGRESQL_PASSWORD}} pg_restore -Fc -U $POSTGRESQL_USERNAME -d $POSTGRESQL_DATABASE /tmp/db.dump'
docker exec "$container" rm -f /tmp/db.dump
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the input. I will forward this to the documentation team. 

Our chart documentation is here: https://github.com/bitnami/charts-docs/tree/main/charts/postgresql-ha

In case you want to contribute with a PR, please let us know and we will review it :D
