### ISSUE TITLE
DETAIL] PQping() returned "PQPING_NO_RESPONSE" on several productions

### ISSUE THREAD

**Issue by TamarNR** [bitnami/bitnami-docker-postgresql-repmgr#118]
### Name and Version

bitnami/postgresql-repmgr:13.3.0-debian-10-r22

### What steps will reproduce the bug?

I have several productions where I exprience from time to time the following problem:
The standby is found to be in a state "running as primary", the primary however is still running as primary, as expected.

When I enter the logs, I see this on the "good" Primary:

> 2022-03-15 11:06:50.286 GMT [344] LOG:  could not receive data from client: Connection reset by peer
> 2022-03-15 11:06:50.286 GMT [344] LOG:  unexpected EOF on standby connection
> [2022-03-15 11:06:50] [DEBUG] child node: 1001; attached: no
> [2022-03-15 11:06:50] [NOTICE] standby node "octopuspg-1" (ID: 1001) has disconnected
> 

On the standby running as primary, I can see that some time ago it lost its contact to the primary for some reason:

> [2022-03-15 11:05:57] [WARNING] unable to ping "user=octopusrepmgr password=oct-DBA+2020 host=192.168.150.33 dbname=repmgr port=5000 connect_timeout=5"
> [2022-03-15 11:05:57] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
> [2022-03-15 11:05:57] [WARNING] unable to connect to upstream node "octopuspg-0" (ID: 1000)
> [2022-03-15 11:05:57] [INFO] checking state of node "octopuspg-0" (ID: 1000), 1 of 3 attempts
> [2022-03-15 11:06:02] [WARNING] unable to ping "user=octopusrepmgr password=oct-DBA+2020 connect_timeout=5 dbname=repmgr host=192.168.150.33 port=5000 fallback_application_name=repmgr"
> 
> 

and so it declares itself as primary, eventhough the original primary did not fail.

I'm not sure how to debug this and understand what caused the standby to loose ping, or perhaps setup a larger timeout for the ping attempts?

Any suggestion is appreciated.

Thanks,
Tamar

### What is the expected behavior?

Not to loose pint to the primary

### What do you see instead?

lStandy running in a mode "running as primary"

**Comment by javsalgar** [comment]
Hi,

It seems that there might be some connection issue in the Kubernetes network. Checking the repmgr documentation, it seems there are these configuration values:

```
reconnect_attempts
The number of attempts (default: 6) will be made to reconnect to an unreachable upstream node before initiating a failover.

There will be an interval of reconnect_interval seconds between each reconnection attempt.

reconnect_interval
Interval (in seconds, default: 10) between attempts to reconnect to an unreachable upstream node.

The number of reconnection attempts is defined by the parameter reconnect_attempts.


```

It seems that there are 6 reconnection attempts of 10 seconds each. Would it make sense to allow increasing these values for your use case?
