### ISSUE TITLE
Initializing a new pgpool/postgresql database results on a "kind does not match between main(53) slot[1] (45)"

### ISSUE THREAD

**Issue by flixman** [bitnami/bitnami-docker-postgresql-repmgr#119]
### Name and Version

* docker.io/bitnami/postgresql-repmgr:11
* docker.io/bitnami/pgpool:4

### What steps will reproduce the bug?

1. I use the docker-compose.yml file provided by bitnami on the pgpool repo, https://github.com/bitnami/bitnami-docker-pgpool/blob/master/docker-compose.yml
2. My setup is: pgpool and one postgresql instance running on node0, and 2 postgresql additional instances running on two different nodes.
3. I start the setup in all nodes with a complete clean setup: docker-compose down -v && docker-compose up.
4. Before going ahead, I make sure that all nodes are reporting healthy through "show pool_nodes;" in the head node.
5. I execute a script that creates a database, a table, and populates it with two records. After that it retrieves the records through pgpool and through each node, to make sure the replication works.

### What is the expected behavior?

The database is created and populated, and the records show up through both the pgpool connection and through the connection to each database engine.

### What do you see instead?

Many times, the database creation fails and on the head node I get the following message: "kind does not match between main(53) slot[1] (45)".

### Additional information

When that happens a first time, the likelyhood of having it every time since that moment is high. Strangely enough, seem as if there was some dependency with respect to the environment. I am running this setup on 3 VMs in Azure, with 4 cores each and 16 GB of RAM, which should be more than enough for the dummy database I am creating.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami postgresql-repmgr container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by foarsitter** [comment]
If I recall correctly this is a problem with the amount of connections that are being used. There is an excellent article on  the pgpool wiki about it: https://pgpool.net/mediawiki/index.php/Relationship_between_max_pool,_num_init_children,_and_max_connections
