### ISSUE TITLE
Guidance on `standby switchover` when in manual failover mode?

### ISSUE THREAD

**Issue by ross-nordstrom** [bitnami/bitnami-docker-postgresql-repmgr#121]
### Name and Version

bitnami/postgresql-repmgr:14.3.0-debian-10-r22

### What is the problem this feature will solve?

When running a 2-node replication cluster in kubernetes, in `failover=manual` mode, I cannot from the `switchover` command because it requires SSH access to the primary node.

```shell
I have no name!@postgres-node-1-7d65d4cb4-94wvm:/$ /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show --compact
postgresql-repmgr 15:37:32.94 
postgresql-repmgr 15:37:32.94 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 15:37:32.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 15:37:32.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 15:37:32.94 

 ID   | Name            | Role    | Status    | Upstream        | Location | Prio. | TLI
------+-----------------+---------+-----------+-----------------+----------+-------+-----
 1000 | postgres-node-0 | primary | * running |                 | default  | 100   | 1   
 1001 | postgres-node-1 | standby |   running | postgres-node-0 | default  | 100   | 1   
```

```shell
I have no name!@postgres-node-1-7d65d4cb4-94wvm:/$ /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf standby switchover
postgresql-repmgr 15:37:45.83 
postgresql-repmgr 15:37:45.83 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 15:37:45.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 15:37:45.84 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 15:37:45.84 

WARNING: unable to connect to remote host "postgres-node-0" via SSH
ERROR: unable to connect via SSH to host "postgres-node-0", user ""
I have no name!@postgres-node-1-7d65d4cb4-94wvm:/$ 
```

It doesn't look like any ssh daemon is running, so I'm guessing the image would need to be updated to support this?

```shell
I have no name!@postgres-node-0-54fdf78bbc-p8d2p:/$ ps aux | grep sshd
1001       810  0.0  0.0   6080   884 pts/0    S+   15:34   0:00 grep sshd
```

Is `switchover` already supported? If so, any guidance on setting it up?  If not, is this something you plan on adding?

### What is the feature you are proposing to solve the problem?

Run an ssh daemon (or whatever is needed for repmgr) so the `standby switchover` command can be used in a containerized environment.

### What alternatives have you considered?

My workaround is to force a failover by bringing nodes down/up in a controlled way, but this introduces down time and more manual steps that could be messed up.

**Comment by fmulero** [comment]
So sorry @ross-nordstrom about my very late response. I missed this issue in my board.

Currently there is no support for `switchover` because it requires a passwordless SSH connection to the current primary.

I suggest you take a glance to [bitnami/postgresql-ha chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha), the postgresql statefulset has a [preStop hook](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/hooks-scripts-configmap.yaml) to wait for the new primary node.

I hope it helps
