### ISSUE TITLE
Cannot start a lone surviving standby node: `Waiting for primary...`

### ISSUE THREAD

**Issue by ross-nordstrom** [bitnami/bitnami-docker-postgresql-repmgr#122]
### Name and Version

bitnami/postgresql-repmgr:14.3.0-debian-10-r22
_**[Edit]** Reproduced below in bitnami/postgresql-repmgr:14.3.0-debian-11-r4_

### What steps will reproduce the bug?

When running a ~2-node replication cluster~ primary+standby in kubernetes, in failover=manual mode, I cannot recover the lone-surviving standby node if it restarts.  This is because it comes up and decides it can't/shouldn't do anything without a primary node _(❕ defeating the purpose of standby!)_.

1. Run a primary/standby pair (I'm running as two k8s deployments)
2. Simulate a disaster (bring down the primary)
   ```shell
   kubectl scale --replicas=0 deployments/postgres-node-0
   kubectl delete pvc data-postgres-node-0
   ```
3. Simulate a disaster (restart the surviving standby)
  * _This is the problem. If you don't do this, you can shell in and run `standby promote`_
   ```shell
   kubectl rollout restart deployment/postgres-node-1
   ```
4. 🐞  Watch the logs as the standby fails to come up... it refuses to because it "needs" the primary.  
5. 🐞 Luckily I can still shell in, but all commands fail because the local psql database isn't available. This also prevents me running the `standby promote` command and recovering the system

![image](https://user-images.githubusercontent.com/3299155/173624599-4e1f866e-b1df-4d3c-888f-1ae3de7e60de.png)
![image](https://user-images.githubusercontent.com/3299155/173625001-8a85bd9a-c630-4df1-a71d-298132f32e2b.png)

### What is the expected behavior?

The lone surviving standby node should come up and allow me to shell in and run `standby promote`.  OR give some other mechanism to promote it.

### What do you see instead?

Cry 😅.  I haven't figured out another way to recover from this situation.  In a production environment, I would have to 🤞 cross my fingers that the EBS volume wasn't lost and I can _eventually_ recover if the disaster resolves itself, by running both postgres nodes.  This is (obviously?) not acceptable for a standby setup.

### Additional information

I've also tried changing the ENV vars to "trick" the node into thinking it's primary, but that doesn't do anything useful. It just changes the failure logs on startup, so now it goes into a fail cycle. I end up getting a 10s window to shell in and try running a repmgr command, but they fail.

![image](https://user-images.githubusercontent.com/3299155/173623899-2c26d56f-5b4e-4393-9fc5-921738100936.png)
_:memo: Side note: it's a shame it prints the DB password in the logs_

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Could you share the yaml of the two deployments so we can consistently reproduce the issue?

**Comment by ross-nordstrom** [comment]
👍 I'll work on a minimal reproduction and get back to you with it

**Comment by ross-nordstrom** [comment]
Here you go, hopefully this is clear and minimal enough!
https://github.com/ross-nordstrom/bitnami-docker-postgresql-repmgr-failover

Here's what it produces:
* [Happy path works](https://user-images.githubusercontent.com/3299155/173935887-6c8ec4c8-82c8-4d3c-a765-f5c99eed340c.png)
* [but it fails if node-1 restarts before promote](https://user-images.githubusercontent.com/3299155/173936451-fce51d29-ff41-4b18-b194-de87c5523ea5.png)

**Comment by amilanoski** [comment]
I am hitting a similar issue here https://github.com/bitnami/charts/issues/10821 using the bitnami postgresql-ha cluster helm chart.

**Comment by rafariossaa** [comment]
Hi,

| When running a 2-node replication cluster in kubernetes, in failover=manual mode, I cannot recover the lone-surviving standby node if it restarts.

Not sure what you mean by `2-node replication cluster` , does it mean you have 3 nodes in total (1 primary + 2 secondary nodes) or does it means you have 1 primary node + 1 secondary node ?

**Comment by ross-nordstrom** [comment]
1 primary, 1 secondary

**Comment by rafariossaa** [comment]
Could you try with 1 primary + 2 secondary ? Most of the time cluster decisions need a minimun quorum and that is not possible with only 2 nodes.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
