### ISSUE TITLE
pgBackRest not installed

### ISSUE THREAD

**Issue by bobindagit** [bitnami/bitnami-docker-postgresql-repmgr#123]
### Name and Version

bitnami/postgresql-repmgr:14.4.0

### What steps will reproduce the bug?

1. `psql -U postgres` (with POSTGRESQL_POSTGRES_PASSWORD password)
2. `pgbackrest version` (nothing happens)

### What is the expected behavior?

working pgbackrest

### What do you see instead?

nothing, it simply didn't install in the container

### Additional information

There are envs installed for pgbackrest, but nothing more. I can't backup with this tool.

**Comment by alemorcuq** [comment]
The image does not include `pgbackrest`. What are those envs that gave you that impression?

**Comment by bobindagit** [comment]
> 

14/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh - line 362-367

**Comment by alemorcuq** [comment]
`pgbackrest` is included in the `bitnami/postgresql` image, but not in this `bitnami/postgresql-repmgr` image. I'm not sure it is compatible with repmgr, but I will create an internal task to investigate it.

**Comment by bobindagit** [comment]
> `pgbackrest` is included in the `bitnami/postgresql` image, but not in this `bitnami/postgresql-repmgr` image. I'm not sure it is compatible with repmgr, but I will create an internal task to investigate it.

Thank you so much. I will use barman for backup tasks.
