### ISSUE TITLE
Unable to exec repmgr

### ISSUE THREAD

**Issue by gnomus** [bitnami/bitnami-docker-postgresql-repmgr#18]
**Description**
Executing repmgr using `docker exec` or `kubectl exec` fails with:
```
$ docker exec pg-0 repmgr
could not get current user name: Success
```

**Steps to reproduce the issue:**

1. Run Container
2. docker exec containername repmgr

**Describe the results you received:**
repmgr exits with an Error

**Describe the results you expected:**
repmgr should work

**Additional information you deem important (e.g. issue happens only occasionally):**
This apperently happens because of the User 1001 having no Passwd Entry.
If you add a User with ID 1001 repmgr works fine.

See: https://github.com/2ndQuadrant/repmgr/blob/7be1ca05cb4c2d1f8fc9b64a0b7b82bc09eb5b45/repmgr-client.c#L178

**Version**

- Output of `docker version`:
omitted, not relevant

- Output of `docker info`:
omitted, not relevant

- Output of `docker-compose version` (if applicable):
omitted, not relevant

**Comment by dani8art** [comment]
Hi @gnomus , you are right, repmgr needs a user name to be run as the container is non-root we use `nss_wrapper` to provide it but `nss_wrapper` is configured in `/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh` so when we use `exec` we skip the `nss_wrapper` configuration. 

You could try to run:

```bash
$ docker exec -ti pg-0 /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr --help
```

**Comment by gnomus** [comment]
Yes that works, thank you.
Maybe it would be good to have this documented in the README ?

**Comment by dani8art** [comment]
Sure, we have opened an internal task to do that for all of our non-root containers using `nss_wrapper`. Thank you so much for your feedback!

**Comment by gnomus** [comment]
Ok thank you.

**Comment by vishrantgupta** [comment]
After exec into the pod, you could do:

```
/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster  show
```

**Comment by dblife1024** [comment]
/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr --version
