### ISSUE TITLE
Question: Standby pod executes `repmgr standby clone --force` after each restart. Any way to speed up standby recovery after restart?

### ISSUE THREAD

**Issue by kostyaplis** [bitnami/bitnami-docker-postgresql-repmgr#20]
**Description**
We evaluating bitnami `postgresql-ha` in our dev environment running on AWS EKS 1.15
Installed with [bitnami/postgresql-ha](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha) helm chart.
We use postgres `10.12.0-debian-10-r57` and pgpool `4.1.1-debian-10-r62` 
Most of the helm values are default, except of user/password secrets and those listed below:
```yaml
postgresql:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
pgpool:
  useLoadBalancing: false
  replicaCount: 2
persistence:
  enabled: true
  size: 150Gi
```

Our dev database is about 120GB in size.

Emulating standby pod failure by running
```bash
kubectl delete pod postgresql-ha-postgresql-1
```
After pod restart it takes about 30 minutes to fully copy over all the data from primary node.
`repmgr standby clone --force` command initiated from [here](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/cd24d126c7377f7e49bdc28628de48d3c45ca758/10/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L547)  and I understand there is no way around it?

Thats the reason why we have `livenessProbe` disabled (maybe `readinessProbe` should be enabled, please advise). Otherwise, standby clone would never finish. Pod will be restarted after some time, accordingly to readiness threshold, and replication starts over, again and again.

Another Issue we faced - restarting standby node `postgresql-ha-postgresql-1` and primary node `postgresql-ha-postgresql-0` several minutes after, we lost all the data on BOTH persistent volumes. It was just wiped out. 

So my question - is there any option to consider existing data on standby node to speed up its rejoin to cluster after restart and potentially prevent complete data loss?
Thanks in advance!

Below attached standby node logs till the moment the existing data got wiped and `pg_basebackup` started to clone data from scratch:

```bash
postgresql-repmgr 07:45:39.75 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 07:45:39.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 07:45:39.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 07:45:39.76 Send us your feedback at containers@bitnami.com
postgresql-repmgr 07:45:39.76
postgresql 07:45:39.76 DEBUG ==> Configuring libnss_wrapper...
postgresql-repmgr 07:45:39.77 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
repmgr 07:45:39.82 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql 07:45:39.82 INFO  ==> Validating settings in POSTGRESQL_* env vars..
repmgr 07:45:39.82 INFO  ==> Querying all partner nodes for common upstream node...
repmgr 07:45:39.83 DEBUG ==> Checking node 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'...
repmgr 07:45:39.87 DEBUG ==> Pretending primary role node - 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'
repmgr 07:45:39.87 DEBUG ==> Pretending primary set to 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'!
repmgr 07:45:39.87 DEBUG ==> Checking node 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'...
psql: could not connect to server: Connection refused
	Is the server running on host "postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.data.svc.cluster.local" (10.3.60.30) and accepting
	TCP/IP connections on port 5432?
repmgr 07:45:39.88 DEBUG ==> Skipping: failed to get primary from the node 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'!
repmgr 07:45:39.89 INFO  ==> Auto-detected primary node: 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'
repmgr 07:45:39.89 DEBUG ==> Primary node: 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'
repmgr 07:45:39.90 INFO  ==> Preparing PostgreSQL configuration...
repmgr 07:45:39.90 DEBUG ==> Injecting a new postgresql.conf file...
postgresql 07:45:39.90 INFO  ==> postgresql.conf file not detected. Generating it...
repmgr 07:45:39.95 DEBUG ==> Injecting a new pg_hba.conf file...
repmgr 07:45:39.95 INFO  ==> Preparing repmgr configuration...
repmgr 07:45:39.96 DEBUG ==> Node ID: '1001', Rol: 'standby', Primary Node: 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432'
repmgr 07:45:39.96 INFO  ==> Initializing Repmgr...
repmgr 07:45:39.96 INFO  ==> Waiting for primary node...
repmgr 07:45:39.96 DEBUG ==> Wait for schema repmgr.repmgr on 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local:5432', will try 6 times with 10 delay seconds (TIMEOUT=60)
repmgr 07:45:39.99 DEBUG ==> Schema repmgr.repmgr exists!
repmgr 07:45:39.99 INFO  ==> Cloning data from primary node...
NOTICE: destination directory "/bitnami/postgresql/data" provided
INFO: connecting to source node
DETAIL: connection string is: host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local port=5432 user=repmgr dbname=repmgr
DETAIL: current installation size is 118 GB
DEBUG: 2 node records returned by source node
DEBUG: connecting to: "user=repmgr password=XXXXXXX connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local port=5432 fallback_application_name=repmgr"
DEBUG: upstream_node_id determined as 1000
NOTICE: checking for available walsenders on the source node (2 required)
NOTICE: checking replication connections can be made to the source server (2 required)
WARNING: directory "/bitnami/postgresql/data" exists but is not empty
NOTICE: -F/--force provided - deleting existing data directory "/bitnami/postgresql/data"
DEBUG: replication slot "repmgr_slot_1001" exists but is inactive; reusing
NOTICE: starting backup (using pg_basebackup)...
INFO: executing:
  /opt/bitnami/postgresql/bin/pg_basebackup -l "repmgr base backup"  -D /bitnami/postgresql/data -h postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.data.svc.cluster.local -p 5432 -U repmgr -c fast -X stream -S repmgr_slot_1001
```

**Comment by rafariossaa** [comment]
Hi,
  First of all thanks for you questions.
  The data need to be replicated from the master node, so it is going to take a while to send the 120GB. Instead of disabling the probes you can tune the timers in https://github.com/bitnami/charts/blob/0544d8cdc65662a8b42eb758d9e327d5b58496d4/bitnami/postgresql-ha/values.yaml#L192 . 
If you don't set them, it would take the kubernetes default values hence the restarts you observed.

 Could you try it and share your findings ?

**Comment by kostyaplis** [comment]
Hi @rafariossaa, 
Thanks for your prompt reply!

Yes, I definitely can adjust `readinessProbe` to make sure that pod has at least 20-30 mins to replicate the data upon restart.
I was just thinking that I'm missing something and there is a way to let `repmgr` consider existing data, compare WAL positions, whatever...
I'll experiment with increased values for `readinessProbe`.
Hopefully this should eliminate possibility to loose all the data if both nodes got restarted within several minutes timeframe.

**Comment by rafariossaa** [comment]
Hi @kostyaplis ,
  Please don't hesitate to share your findings, those could be useful for other users with a similar use case.

Thank forehand.

**Comment by kostyaplis** [comment]
Hi @rafariossaa 
I've end up with enabled `readinessProbe` and disabled `livenessProbe`
```yaml
postgresql:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: true
```

I think there is no reason to set `livenessProbe` thresholds to at least 30 mins to make sure we have enough time to finish replication on standby node restart. As it defeats `livenessProbe` purpose. We just should use monitoring and alerting if we do care about our standby node status.

[startupProbe](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes) would be a proper option to handle long application start as (unlike `readinessProbe`) it disables `livenessProbe` until container fully started and replication finished. 
But `startupProbe` only available in kubernetes 1.16 and above.

**Comment by uberkelium** [comment]
I am running into this issue now with "postgresql-ha" and would like to know an answer to question from @kostyaplis which was:

> Another Issue we faced - restarting standby node postgresql-ha-postgresql-1 and primary node postgresql-ha-postgresql-0 several minutes after, we lost all the data on BOTH persistent volumes. It was just wiped out.

> So my question - is there any option to consider existing data on standby node to speed up its rejoin to cluster after restart and potentially prevent complete data loss?
Thanks in advance!

Is it seriously impossible to clone the data from the primary node or use existing data rather than outright delete everything? I do not want the standby nodes to copy **everything** from the primary node every single time. Can we just copy the data directory from primary to secondary, then when secondary starts up, it checks the differences between the two and syncs only those differences?

**Comment by rafariossaa** [comment]
Hi @uberkelium ,
  If you copy the data from the primary to the secondary you will need to wait that time, time wise and transfer wise what you propose will be the same, and also it adds that later you need to compare and start.
  There is another way of doing this that is mounting the master data files on other node, and the run a synchronization process. In kubernetes, the storage are related to the kubernetes cluster node, and nodes where master and slave pods are running could be different. In this scenario you won't be able to mount the master pod's filesystem onto the slave pod and run a synchronization pod. The wipe and sync, it is a solution for this problem.

Hope this helps.

**Comment by uberkelium** [comment]
> Hi @uberkelium ,
> If you copy the data from the primary to the secondary you will need to wait that time, time wise and transfer wise what you propose will be the same, and also it adds that later you need to compare and start.
> There is another way of doing this that is mounting the master data files on other node, and the run a synchronization process. In kubernetes, the storage are related to the kubernetes cluster node, and nodes where master and slave pods are running could be different. In this scenario you won't be able to mount the master pod's filesystem onto the slave pod and run a synchronization pod. The wipe and sync, it is a solution for this problem.
> 
> Hope this helps.

@rafariossaa
Copying the data files is fine and much faster, because it is faster to copy the files than have PostgreSQL delete the data directory and sync from the primary node. This also works better for block device cloning. Not an issue for me as I have tested it

What do you mean by "run a synchronization process"? If I copy the data files to the secondary node, is there a process to sync the standby node without deleting the data directory?

**Comment by rafariossaa** [comment]
@uberkelium 
  Have in mind that this container is not meant only to be run in docker but also in kubernetes. In kubernetes, you have delegated the control of where the pods are and the filesystem to it, and also it is dependent on the kubernetes cluster you are running and the storage options you may have.
  In kuberentes, to copy files you will need to mount the filesystem from pod A on pod B, and you can not always do this. Our container does not have SSH, so the only way is mounting a the master's filesystem on the replica and you won't be able to do this always.  
  On the other hand, letting postgresql delete and clone the data could be not the fastest way, but it is going to work in all the scenarios.
  As you can see in the function `postgresql_slave_init_db` we are using `pb_basebackup` to copy the files from the master. Take also into account that to have a consistent copy of the master filesystem you need to stop postgresql and with `pg_basebackup` you can make a hot copy.

  If you would like to make a contribution to improve the container and chart, PR are welcomed and we will be glad to review and merge them.

**Comment by uberkelium** [comment]
> @uberkelium
> Have in mind that this container is not meant only to be run in docker but also in kubernetes. In kubernetes, you have delegated the control of where the pods are and the filesystem to it, and also it is dependent on the kubernetes cluster you are running and the storage options you may have.
> In kuberentes, to copy files you will need to mount the filesystem from pod A on pod B, and you can not always do this. Our container does not have SSH, so the only way is mounting a the master's filesystem on the replica and you won't be able to do this always.

Yes, I understand your concerns about the mechanics of copying. As I said in my previous post, low-level copying is a non-issue because I am using rook-ceph in Kubernetes which can clones persistent volumes while still in use, which completely removes the concern about mounting pods. Letting the storage solution handle file replication is much faster than having PostgreSQL parse incoming data through the network and I have already tested it, so I would not worry about your point very much. The only issue is that the cloned data for a hot backup is a few seconds old, so that set me on this journey to discover a solution to do a diff restore.

> As you can see in the function `postgresql_slave_init_db` we are using `pb_basebackup` to copy the files from the master. Take also into account that to have a consistent copy of the master filesystem you need to stop postgresql and with `pg_basebackup` you can make a hot copy.

Thanks for describing context on pg_basebackup. The issue is that I tried shutting down the pods, cloned the primary disk to secondaries, and then tried starting all 3 nodes. I have a guarantee that the data directory is identical between nodes on startup, but still the secondaries go through the full cloning process (because of repmgr standby clone, obviously). I think this basically achieves the same goal as pg_basebackup.

> If you would like to make a contribution to improve the container and chart, PR are welcomed and we will be glad to review and merge them.

I will think about how to proceed on this issue. Might take a long time. From [#49 (comment)](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/49#issuecomment-717846202), it seems the next step is to make a custom image of bitnami-docker-postgresql-repmgr, remove `repmgr standby clone` and replace with `repmgr` node rejoin`

**Comment by rafariossaa** [comment]
Hi,
  I am happy that clarify a little bit on the issue.
  This chart needs to be as generic as possible to work in very different scenarios. If you can make the changes to use copying and change the image accordingly, that would be great.
  If it happens that you send a PR, please link this issue so there will be some background.

**Comment by foarsitter** [comment]
@hi-usui any luck on your 'node rejoin' image?
