### ISSUE TITLE
Witness node

### ISSUE THREAD

**Issue by TamarNR** [bitnami/bitnami-docker-postgresql-repmgr#24]
Hi,

Is there a support for witness node?
According to repmgr documentation 
"By creating a witness server in the same location (data centre) as the primary, if the primary becomes unavailable it's possible for the standby to decide whether it can promote itself without risking a "split brain" scenario: if it can't see either the witness or the primary server, it's likely there's a network-level interruption and it should not promote itself.  "

Thanks

**Comment by andresbono** [comment]
Hi @TamarNR, thanks for showing interests on this container. About the feature that you are describing, we have not explored it yet. We are open to receive PRs, contributions are more than welcome! So if you think this feature is interesting, you can start drafting a PR and we will be more than happy to review it.

**Comment by TamarNR** [comment]
Thanks
