### ISSUE TITLE
Add parameters to repmgr.conf and other configuration files

### ISSUE THREAD

**Issue by TamarNR** [bitnami/bitnami-docker-postgresql-repmgr#25]
Hi,

I wanted to know if there is a problem with changing the repmgr.conf created by you when the container runs (by using a volume for it of course).

We would like to add for example the parameter "log_file" in order to see a more detailed log of the repmgr daemon. Also we need a more detailed log for postgres (the same we were used to see when no replica/repmgr was deployed).

Thanks,
Tamar

**Comment by juan131** [comment]
Hi @TamarNR 

You can use your custom configuration files. Please check the section below in the README.md that explains the process to do so:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr#configuration-file

**Comment by TamarNR** [comment]
Hi juan131,

Thanks for your answer.

I am still having problems.

I created a directory on my host, with the specified proper permissions, and in it I put postgresql.conf with a change to the parameter "shared_buffers".

I tried to execute this command then - 
where "/home/deploy/bitnami_conf" is the directory I created on my host and contains my postgresql.conf

docker run --detach --name pg-0  -v /home/deploy/bitnami_conf:/opt/bitnami/postgresql/conf/ \
  -p 0.0.0.0:5433:5432 \
  --env REPMGR_PARTNER_NODES=10.97.7.140,10.97.7.97 \
  --env REPMGR_NODE_NAME=pg-0 \
  --env REPMGR_NODE_NETWORK_NAME=10.97.7.140 \
  --env REPMGR_PRIMARY_HOST=10.97.7.97 \
  --env REPMGR_PORT_NUMBER=5433 \
  --env REPMGR_PRIMARY_PORT=5433 \
  --env REPMGR_LOG_LEVEL=DEBUG \
  --env REPMGR_PASSWORD=mypassword \
  --env POSTGRESQL_PASSWORD=mypassword \
  bitnami/postgresql-repmgr:latest
  
still psql "show shared_buffers;" command does not show the parameter change.
In addition, I cannot see the parameter changed in postgresql.conf under /opt/bitnami/postgresql/conf
 
 The run command specified above is what was intended by the README file? 
 or am I missing something?
 
 Also, the documentation says: 
 "The image looks for the repmgr.conf, postgresql.conf and pg_hba.conf files in /opt/bitnami/repmgr/conf/ and /opt/bitnami/postgresql/conf/. You can mount a volume at /bitnami/repmgr/conf/ and copy/edit the configuration files in the /path/to/custom-conf/"
 
So is it /opt/bitnami/repmgr/conf/ or /bitnami/repmgr/conf/ ?
 
 Thanks,
 Tamar

**Comment by TamarNR** [comment]
OK, figured it out...

indeed you need to map the all configuration files to /bitnami/repmgr/conf/

for example:
docker run --detach --name pg-0 -v /home/myuser/bitnami_conf:/bitnami/repmgr/conf/    etc.

Thanks,
Tamar
