### ISSUE TITLE
Postgresql cannot start after restore from backup

### ISSUE THREAD

**Issue by hennning** [bitnami/bitnami-docker-postgresql-repmgr#26]
**Description**

We had a hardware failure affecting our primary postgresql node in a K8S cluster.
After restoring the node our postgresql-ha cluster won't start.

Logs give the following error:
[ERROR] unable connect to upstream node (ID: 1001), terminating

This happens right away, when the container is created and I'm unable to run any commands on it.
We have no other containers running in the cluster to run commands from either.

**Steps to reproduce the issue:**

1. Create Postgresql-ha using the old helm values and old volumes
2. The postgresql-ha-postgresql-0 pod failes with the error above

**Describe the results you received:**

postgresql-repmgr 19:24:43.56 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 19:24:43.58 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 19:24:43.58 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 19:24:43.59 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 19:24:43.64 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 19:24:43.64 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 19:24:43.65 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 19:24:43.69 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 19:24:43.70 INFO  ==> Initializing Repmgr...
postgresql-repmgr 19:24:43.70 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 19:24:43.70 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql-repmgr 19:24:43.71 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 19:24:43.71 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 19:24:43.73 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 19:24:43.74 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 19:24:43.75 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 19:24:43.76 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 19:24:44.09 INFO  ==> ** Starting repmgrd **
[2020-07-23 19:24:44] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2020-07-23 19:24:44] [NOTICE] starting monitoring of node "postgresql-ha-postgresql-0" (ID: 1000)
[2020-07-23 19:24:44] [ERROR] connection to database failed
[2020-07-23 19:24:44] [DETAIL]
could not translate host name "postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.postgresql-ha.svc.k8s.***" to address: Name or service not known

[2020-07-23 19:24:44] [DETAIL] attempted to connect using:
  user=*** password=*** connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.postgresql-ha.svc.k8s*** port=5432 fallback_application_name=repmgr
[2020-07-23 19:24:44] [ERROR] unable connect to upstream node (ID: 1001), terminating
[2020-07-23 19:24:44] [HINT] upstream node must be running before repmgrd can start

**Describe the results you expected:**

I expect postgresql to startup or create all pods allowing the primary one to start the database successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:34 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:11:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Output of `docker info`:

Client:
 Debug Mode: false

Server:
 Containers: 113
  Running: 94
  Paused: 0
  Stopped: 19
 Images: 87
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-40-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.22GiB
 Name: qsys-k8s-worker01
 ID: JSKN:2B6F:MIHC:4AOA:A2V6:XH75:DMN6:U6J4:T7NS:IR3V:TVBS:ZPXD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running K8S on Hyper-V cluster with Rancher and RKE.

**Comment by javsalgar** [comment]
Hi,

Which version of the chart are you using? It seems that it is because it is trying to access psql node 1 but that is not ready yet. I believe that @rafariossaa applied some fixes to avoid that.

**Comment by hennning** [comment]
We should be using 3.4.9.

But the thing is we had an incident a few weeks ago where we had to restore the K8S cluster and all the helm charts disappeared (the apps were still there and running).
I have now tried to remove the Postgresql app, and recreate with a the helm chart with the old settings and using the old Persistant Storage volumes.

Now it crashes at postgresql-repmgr 10:09:20.37 INFO  ==> Starting PostgreSQL in background...



We also have backup of the application with Kasten K10, restoring the application from that results in is crashing at:
postgresql-repmgr 10:09:43.76 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 10:09:44.08 INFO  ==> ** Starting repmgrd **
[2020-07-24 10:09:44] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
[2020-07-24 10:09:44] [ERROR] connection to database failed
[2020-07-24 10:09:44] [DETAIL]
could not translate host name "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.postgresql-ha.svc.k8s.***" to address: Name or service not known
[2020-07-24 10:09:44] [DETAIL] attempted to connect using:
  user=*** password=*** connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.postgresql-ha.svc.k8s.*** port=5432 fallback_application_name=repmgr



Is it maybe possible to extract the database from the old Persistent Volume and import it to a fresh install instead?

**Comment by hennning** [comment]
I just realized the reason it crashed a bit earlier when I restored from backup was because the URL was wrong since I had put it in a different namespace. Fixing that puts me at the same spot as my original post, with the error [ERROR] unable connect to upstream node (ID: 1001), terminating

**Comment by hennning** [comment]
> Hi,
> 
> Which version of the chart are you using? It seems that it is because it is trying to access psql node 1 but that is not ready yet. I believe that @rafariossaa applied some fixes to avoid that.

Just saw in the YAML file from the backup that it's version 3.3.1
helm.sh/chart: postgresql-ha-3.3.1

**Comment by hennning** [comment]
Ok, an update from my part.
I've managed to solve the issue, but could someone please verify that this solution is sustainable and won't bite me in the ass later on?

1. 


What I did was mounting the Persistent Volume on a Ubuntu server and copied all files under /bitnami/postgresql/data



I then searched for files containing "postgresql-ha-postgresql-1.postgresql" which is the server Postgres is trying to contact at boot.
I found that the database named 16385 included that phrase in 2 files, so I removed that database from my backup. My guess this is the Repmgr database.

**Comment by javsalgar** [comment]
Hi,

Great to know! Could you also verify the status of the cluster by executing this query on the current master? 

```
select client_addr, state, sent_location, write_location,
        flush_location, replay_location from pg_stat_replication;
```

**Comment by hennning** [comment]
> Hi,
> 
> Great to know! Could you also verify the status of the cluster by executing this query on the current master?
> 
> ```
> select client_addr, state, sent_location, write_location,
>         flush_location, replay_location from pg_stat_replication;
> ```

Hi,
Where am I supposed to run this command?
When running it in Pgadmin against both postgres database and repmgr database I get the following error:
`ERROR:  column "sent_location" does not exist
LINE 1: select client_addr, state, sent_location, write_location,
                                   ^
SQL state: 42703
Character: 28`

**Comment by javsalgar** [comment]
Sorry, could you try with this instead?

```
select * from pg_stat_replication;
````

**Comment by hennning** [comment]
Sure, here you go.

153692	"16384"	"***"	"postgresql-ha-postgresql-1"	"10.42.4.185"		50000	"2020-07-29 09:29:20.392767+00"		"streaming"	"0/3F000F08"	"0/3F000F08"	"0/3F000F08"	"0/3F000F08"				0	"async"	"2020-07-29 09:31:38.066432+00"
154067	"16384"	"***"	"postgresql-ha-postgresql-2"	"10.42.5.156"		46470	"2020-07-29 09:30:49.524345+00"		"streaming"	"0/3F000F08"	"0/3F000F08"	"0/3F000F08"	"0/3F000F08"				0	"async"	"2020-07-29 09:31:38.068062+00"

**Comment by javsalgar** [comment]
Hi,

So it seems that it is working well, as the other nodes are detected.

**Comment by KaKeimei** [comment]
[2020-08-18 12:48:09] [ERROR] unable connect to upstream node (ID: 1001), terminating
[2020-08-18 12:48:09] [HINT] upstream node must be running before repmgrd can start
[2020-08-18 12:48:09] [INFO] repmgrd terminating...

facing the same problem here. Trying to restore the master node without other nodes, and It failed to restore the master because the second doesnot exist yet

**Comment by javsalgar** [comment]
Hi,

What version of the chart you are using? We added improvements in order to avoid deadlocks. Could you confirm that you are using the latest version?

**Comment by KaKeimei** [comment]
> Hi,
> 
> What version of the chart you are using? We added improvements in order to avoid deadlocks. Could you confirm that you are using the latest version?

Hi, I was using 3.5.5. I fixed the problem by a little bit tricky way, used the bitnami postgresql chart to start up the database and updated the repmgr node record manually, and then change back to ha chart

**Comment by javsalgar** [comment]
Hi,

That's strange. Please let us know if this happens again, we fixed most of the deadlock issues so far.

**Comment by KaKeimei** [comment]
> Hi,
> 
> That's strange. Please let us know if this happens again, we fixed most of the deadlock issues so far.

Of course, thank you guys
