### ISSUE TITLE
Inconsistent parameters between entrypoint scripts and Repmgr when they start Postgres.

### ISSUE THREAD

**Issue by jxl4650152** [bitnami/bitnami-docker-postgresql-repmgr#33]
**Description**
Hi there,

When the image's entrypoint scripts [start Postgres](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/402bb8c5da5b53a187adcc6fbb04b82c57189e18/10/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L718), it uses several commandline arguments to specify data directory, config file .etc,  separately.
But when Repmgr executes `standby follow` action, it needs to [restart Postgres](https://github.com/2ndQuadrant/repmgr/blob/3945314e6597f4e30b3a09d725c620a3f679f019/repmgr-action-standby.c#L3362) and may use different arguments. In my project, Repmgr doesn't add the `--config-file` argument as entrypoint script does, which makes Postgres starting process failed.

Some workarounds:
1.  Exposing [service commands](https://repmgr.org/docs/4.0/configuration-service-commands.html) as environment variables.
2. Adding [service commands](https://repmgr.org/docs/4.0/configuration-service-commands.html) to Repmgr.conf automatically by the entrypoint scripts.

Thanks

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**
```
NOTICE: starting server using "/opt/bitnami/postgresql/bin/pg_ctl  -w -D '/bitnami/postgresql/data' start"
DEBUG: executing:
  /opt/bitnami/postgresql/bin/pg_ctl  -w -D '/bitnami/postgresql/data' start
DEBUG: result of command was 141 (36096)
DEBUG: local_command(): output returned was:
waiting for server to shut down......... done
waiting for server to start....postgres: could not access the server configuration file "/bitnami/postgresql/data/postgresql.conf": No such file or directory
```

**Describe the results you expected:**
Repmgr restart postgres successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

Postgresql-HA chart version: 3.5.9
postgresql-repmgr version: latest
**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @jxl4650152 ,
Could you elaborate about what is your project doing? are you overriding the image entrypoint?

**Comment by jxl4650152** [comment]
Hi @miguelaeh,
I didn't override the entrypoint. In our project, we have one primary server(node0) and two standby servers (node1, node2). After stopping node0, node1 successfully is prompted as the new primary. But the other standby(node2) cannot follow the new primary(node1). The error message lies in node2's log says:

```
NOTICE: starting server using "/opt/bitnami/postgresql/bin/pg_ctl  -w -D '/bitnami/postgresql/data' start"
DEBUG: executing:
  /opt/bitnami/postgresql/bin/pg_ctl  -w -D '/bitnami/postgresql/data' start
DEBUG: result of command was 141 (36096)
DEBUG: local_command(): output returned was:
waiting for server to shut down......... done
waiting for server to start....postgres: could not access the server configuration file "/bitnami/postgresql/da
```

we solve the problem by manually adding setting in Repmgr.conf file.
```
service_stop_command='/opt/bitnami/postgresql/bin/pg_ctl  -w -D \'/bitnami/postgresql/data\' -o \'--config-file=/opt/bitnami/postgresql/conf/postgresql.conf\' stop'
service_start_command='/opt/bitnami/postgresql/bin/pg_ctl  -w -D \'/bitnami/postgresql/data\' -o \'--config-file=/opt/bitnami/postgresql/conf/postgresql.conf --external_pid_file=/opt/bitnami/postgresql/tmp/postgresql.pid --hba_file=/opt/bitnami/postgresql/conf/pg_hba.conf\' start'
```

**Comment by miguelaeh** [comment]
Hi @jxl4650152 ,
Thank you for sharing your solutions.
I can see in your log that the configuration file is being searched into the volume directory, but it seems that the file doesn't exist, or it doesn't have permissions to be read. I think you are using the Helm Chart, could you share the parameters you are using to install it?
I think that path is wrong since it is searching into `/bitnami/postgresql/data` instead of `/bitnami/postrgesql/conf`.

Also, in the log the last line is cut at the end, could you update the comment so I can see the full path, please?

**Comment by jxl4650152** [comment]
@miguelaeh 
The full log:
```
NOTICE: starting server using "/opt/bitnami/postgresql/bin/pg_ctl  -w -D '/bitnami/postgresql/data' start"
DEBUG: executing:
  /opt/bitnami/postgresql/bin/pg_ctl  -w -D '/bitnami/postgresql/data' start
DEBUG: result of command was 141 (36096)
DEBUG: local_command(): output returned was:
waiting for server to shut down......... done
waiting for server to start....postgres: could not access the server configuration file "/bitnami/postgresql/data/postgresql.conf": No such file or directory
```

**Comment by miguelaeh** [comment]
Could you share the exact command you are using to install the Helm Chart?
