### ISSUE TITLE
How to run docker with --network host ?

### ISSUE THREAD

**Issue by leonidn22** [bitnami/bitnami-docker-postgresql-repmgr#35]
Hi, 

How can I run bitnami/postgresql-repmgr:latest with --network host ?
I have to connect to postgresql from host psql client.

When I try run with network host I get the following log and docker exit:
```
postgresql-repmgr 11:45:00.43 
postgresql-repmgr 11:45:00.44 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 11:45:00.44 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 11:45:00.44 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 11:45:00.44 
postgresql-repmgr 11:45:00.46 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 11:45:00.48 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 11:45:00.49 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 11:45:00.49 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 11:45:18.82 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 11:45:18.83 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 11:45:18.83 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 11:45:18.89 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 11:45:18.90 INFO  ==> Initializing Repmgr...
postgresql-repmgr 11:45:18.90 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 11:45:18.91 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 11:45:18.91 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 11:45:20.25 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 11:45:20.38 INFO  ==> Changing password of postgres
postgresql-repmgr 11:45:20.40 INFO  ==> Creating replication user repmgr
postgresql-repmgr 11:45:20.44 INFO  ==> Configuring replication parameters
postgresql-repmgr 11:45:20.46 INFO  ==> Configuring fsync
postgresql-repmgr 11:45:20.47 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 11:45:20.48 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 11:45:20.53 INFO  ==> Creating repmgr database: repmgr
postgresql-repmgr 11:45:20.80 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 11:45:21.81 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 11:45:21.94 INFO  ==> Registering Primary...
postgresql-repmgr 11:45:35.70 INFO  ==> Stopping PostgreSQL...
```

**Comment by juan131** [comment]
Hi @leonidn22 

Could you please share the whole command you're using to stat the container? It should be sth like this:

```
$ docker run --detach --rm --name pg-0 \
  --network host \
  --env REPMGR_PARTNER_NODES=pg-0 \
  --env REPMGR_NODE_NAME=pg-0 \
  --env REPMGR_NODE_NETWORK_NAME=pg-0 \
  --env REPMGR_PRIMARY_HOST=pg-0 \
  --env REPMGR_PASSWORD=repmgrpass \
  --env POSTGRESQL_PASSWORD=secretpass \
  bitnami/postgresql-repmgr:latest
```

**Comment by leonidn22** [comment]
Hi Juan,

Thank You for replying.
Yes it's exactly what I run and unfortunately it exited after 15 sec.
Here is the output:

[root@server-vertica1 ~]# docker run  --rm --name pg-0 \
>   --network host \
>   --env REPMGR_PARTNER_NODES=pg-0 \
>   --env REPMGR_NODE_NAME=pg-0 \
>   --env REPMGR_NODE_NETWORK_NAME=pg-0 \
>   --env REPMGR_PRIMARY_HOST=pg-0 \
>   --env REPMGR_PASSWORD=repmgrpass \
>   --env POSTGRESQL_PASSWORD=secretpass \
>   bitnami/postgresql-repmgr:latest
postgresql-repmgr 09:33:12.91
postgresql-repmgr 09:33:12.91 Welcome to the Bitnami postgresql-repmgr
container
postgresql-repmgr 09:33:12.92 Subscribe to project updates by watching
https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 09:33:12.92 Submit issues and feature requests at
https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 09:33:12.92
postgresql-repmgr 09:33:12.94 INFO  ==> ** Starting PostgreSQL with
Replication Manager setup **
postgresql-repmgr 09:33:12.96 INFO  ==> Validating settings in REPMGR_* env
vars...
postgresql-repmgr 09:33:12.97 INFO  ==> Validating settings in POSTGRESQL_*
env vars..
postgresql-repmgr 09:33:12.97 INFO  ==> Querying all partner nodes for
common upstream node...
postgresql-repmgr 09:33:33.00 INFO  ==> There are no nodes with primary
role. Assuming the primary role...
postgresql-repmgr 09:33:33.01 INFO  ==> Preparing PostgreSQL
configuration...
postgresql-repmgr 09:33:33.01 INFO  ==> postgresql.conf file not detected.
Generating it...
postgresql-repmgr 09:33:33.09 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 09:33:33.09 INFO  ==> Initializing Repmgr...
postgresql-repmgr 09:33:33.10 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 09:33:33.11 INFO  ==> Custom configuration
/opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 09:33:33.11 INFO  ==> Custom configuration
/opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 09:33:34.60 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:33:34.73 INFO  ==> Changing password of postgres
postgresql-repmgr 09:33:34.75 INFO  ==> Creating replication user repmgr
postgresql-repmgr 09:33:34.78 INFO  ==> Configuring replication parameters
postgresql-repmgr 09:33:34.80 INFO  ==> Configuring fsync
postgresql-repmgr 09:33:34.81 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:33:34.82 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 09:33:34.87 INFO  ==> Creating repmgr database: repmgr
postgresql-repmgr 09:33:35.16 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 09:33:36.17 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:33:36.30 INFO  ==> Registering Primary...
postgresql-repmgr 09:33:55.32 INFO  ==> Stopping PostgreSQL...

Regards,
Leonid.,

**Comment by leonidn22** [comment]
Hi Juan,

Thank You for replying.
Yes it's exactly what I run and unfortunately it exited after 15 sec.
Here is the output:

[root@server-vertica1 ~]# docker run  --rm --name pg-0 \
>   --network host \
>   --env REPMGR_PARTNER_NODES=pg-0 \
>   --env REPMGR_NODE_NAME=pg-0 \
>   --env REPMGR_NODE_NETWORK_NAME=pg-0 \
>   --env REPMGR_PRIMARY_HOST=pg-0 \
>   --env REPMGR_PASSWORD=repmgrpass \
>   --env POSTGRESQL_PASSWORD=secretpass \
>   bitnami/postgresql-repmgr:latest
postgresql-repmgr 09:33:12.91
postgresql-repmgr 09:33:12.91 Welcome to the Bitnami postgresql-repmgr
container
postgresql-repmgr 09:33:12.92 Subscribe to project updates by watching
https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 09:33:12.92 Submit issues and feature requests at
https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 09:33:12.92
postgresql-repmgr 09:33:12.94 INFO  ==> ** Starting PostgreSQL with
Replication Manager setup **
postgresql-repmgr 09:33:12.96 INFO  ==> Validating settings in REPMGR_* env
vars...
postgresql-repmgr 09:33:12.97 INFO  ==> Validating settings in POSTGRESQL_*
env vars..
postgresql-repmgr 09:33:12.97 INFO  ==> Querying all partner nodes for
common upstream node...
postgresql-repmgr 09:33:33.00 INFO  ==> There are no nodes with primary
role. Assuming the primary role...
postgresql-repmgr 09:33:33.01 INFO  ==> Preparing PostgreSQL
configuration...
postgresql-repmgr 09:33:33.01 INFO  ==> postgresql.conf file not detected.
Generating it...
postgresql-repmgr 09:33:33.09 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 09:33:33.09 INFO  ==> Initializing Repmgr...
postgresql-repmgr 09:33:33.10 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 09:33:33.11 INFO  ==> Custom configuration
/opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 09:33:33.11 INFO  ==> Custom configuration
/opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 09:33:34.60 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:33:34.73 INFO  ==> Changing password of postgres
postgresql-repmgr 09:33:34.75 INFO  ==> Creating replication user repmgr
postgresql-repmgr 09:33:34.78 INFO  ==> Configuring replication parameters
postgresql-repmgr 09:33:34.80 INFO  ==> Configuring fsync
postgresql-repmgr 09:33:34.81 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:33:34.82 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 09:33:34.87 INFO  ==> Creating repmgr database: repmgr
postgresql-repmgr 09:33:35.16 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 09:33:36.17 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:33:36.30 INFO  ==> Registering Primary...
postgresql-repmgr 09:33:55.32 INFO  ==> Stopping PostgreSQL...

Regards,
Leonid.,

**Comment by leonidn22** [comment]
Hi,
And using network it works:

[root@server-vertica1 ~]# docker run  --rm --name pg-0 \
>   --network psql-network   \
>   --env REPMGR_PARTNER_NODES=pg-0 \
>   --env REPMGR_NODE_NAME=pg-0 \
>   --env REPMGR_NODE_NETWORK_NAME=pg-0 \
>   --env REPMGR_PRIMARY_HOST=pg-0 \
>   --env REPMGR_PASSWORD=repmgrpass \
>   --env POSTGRESQL_PASSWORD=secretpass \
>   bitnami/postgresql-repmgr:latest
postgresql-repmgr 09:45:22.71 
postgresql-repmgr 09:45:22.71 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 09:45:22.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 09:45:22.72 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 09:45:22.72 
postgresql-repmgr 09:45:22.74 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 09:45:22.76 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 09:45:22.76 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 09:45:22.77 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 09:45:22.79 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 09:45:22.80 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 09:45:22.81 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 09:45:22.88 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 09:45:22.89 INFO  ==> Initializing Repmgr...
postgresql-repmgr 09:45:22.89 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 09:45:22.90 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 09:45:22.90 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 09:45:24.26 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:45:24.39 INFO  ==> Changing password of postgres
postgresql-repmgr 09:45:24.41 INFO  ==> Creating replication user repmgr
postgresql-repmgr 09:45:24.44 INFO  ==> Configuring replication parameters
postgresql-repmgr 09:45:24.47 INFO  ==> Configuring fsync
postgresql-repmgr 09:45:24.48 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:45:24.48 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 09:45:24.53 INFO  ==> Creating repmgr database: repmgr
postgresql-repmgr 09:45:24.81 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 09:45:25.82 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:45:25.95 INFO  ==> Registering Primary...
postgresql-repmgr 09:45:26.08 INFO  ==> Loading custom scripts...
postgresql-repmgr 09:45:26.08 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 09:45:27.10 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 09:45:27.12 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:45:27.25 INFO  ==> ** Starting repmgrd **
[2020-09-09 09:45:27] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2020-09-09 09:45:27] [NOTICE] starting monitoring of node "pg-0" (ID: 1000)
[2020-09-09 09:45:27] [NOTICE] monitoring cluster primary "pg-0" (ID: 1000)

**Comment by leonidn22** [comment]
Hi,

Using docker-compose it is more clear what is going on.

the docker-compose.yml :

version: '3.1'
services:
  pg-0:
    image: 'bitnami/postgresql-repmgr:latest'
    ports:
      - '5432'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=dbadmin
      - POSTGRESQL_PASSWORD=dba12
      - POSTGRESQL_DATABASE=dba12
      - REPMGR_PASSWORD=repmgrpass
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
    volumes:
      - /data01/postgres:/bitnami/postgresql
      - /data01/postgres/conf:/bitnami/postgresql/conf
    network_mode: 'psql-network'
    container_name: "pg-0"

And with network_mode: 'psql-network' it works.
But with network_mode: 'host' I getting Error:

pg-0    | postgresql-repmgr 14:15:08.85 INFO  ==> Configuring fsync
pg-0    | postgresql-repmgr 14:15:08.86 INFO  ==> Stopping PostgreSQL...
pg-0    | postgresql-repmgr 14:15:08.87 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **
pg-0    | 
pg-0    | postgresql-repmgr 14:15:08.90 INFO  ==> Starting PostgreSQL in background...
pg-0    | postgresql-repmgr 14:15:09.02 INFO  ==> ** Starting repmgrd **
pg-0    | [2020-09-09 14:15:09] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
pg-0    | [2020-09-09 14:15:09] [ERROR] connection to database failed
pg-0    | [2020-09-09 14:15:09] [DETAIL] 
pg-0    | could not translate host name "pg-0" to address: Name or service not known
pg-0    | 
pg-0    | [2020-09-09 14:15:09] [DETAIL] attempted to connect using:
pg-0    |   user=repmgr password=repmgrpass connect_timeout=5 dbname=repmgr host=pg-0 port=5432 fallback_application_name=repmgr
pg-0 exited with code 6

What can be a solution?

Regards...
Leonid.,

**Comment by leonidn22** [comment]
Finally I solved it by adding pg-0 to /etc/hosts

**Comment by juan131** [comment]
Great @leonidn22 !!! I'm very glad you were able to solve by your own means. Thanks for sharing the solution, it'll be very helpful for other users trying to use the host network.
