### ISSUE TITLE
custom pg_hba.conf  rewrites on startup

### ISSUE THREAD

**Issue by leonidn22** [bitnami/bitnami-docker-postgresql-repmgr#36]
When I use custom conf files 
- /data01/postgres/conf:/bitnami/postgresql/conf

I can extend postgresql.log with conf.d dir.

But how can I add my custom lines into pg_hba.conf ?

**Comment by carrodher** [comment]
In the following README sections you can see the available methods to customize some configuration files:
- https://github.com/bitnami/bitnami-docker-postgresql-repmgr#configuration-file
- https://github.com/bitnami/bitnami-docker-postgresql-repmgr#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf

**Comment by leonidn22** [comment]
Hi,

Thanks,

I have read it before.
But as I wrote it doesn't work for pg_hba.conf.
It is very important detail.

Regards

10 сент. 2020 г. 9:08 ПП пользователь "Carlos Rodríguez Hernández" <
notifications@github.com> написал:

**Comment by carrodher** [comment]
I am able to follow the steps described here and my custom `pg_hba.conf` is copied and used in the container:

- I created a _pg_hba.conf_ file under `/home/projects/postgresql-repmgr/custom` with a comment
```
 host     all            repmgr    0.0.0.0/0    md5
 host     repmgr         repmgr    0.0.0.0/0    md5
 host     replication      repmgr    0.0.0.0/0    md5
 #hostssl     all             all             0.0.0.0/0               cert
 #hostssl     all             all             ::/0                    cert
 host     all              all       0.0.0.0/0    md5
 host     all              all       ::/0         md5
 local    all              all                    md5
 # This is a comment, let's see if appears inside the container
```

- I provided the proper permissions to the folder:
```console
$ sudo chgrp -R root /home/projects/postgresql-repmgr/custom
$ sudo chmod -R g+rwX /home/projects/postgresql-repmgr/custom
```

- I modified the _docker-compose.yaml_ to mount a volume with the path to the directory where the above file is hosted:
```diff
@ docker-compose.yml:9 @ services:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
+     - /home/projects/postgresql-repmgr/custom:/bitnami/repmgr/conf/
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
@ docker-compose.yml:28 @ services:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
+     - /home/projects/postgresql-repmgr/custom:/bitnami/repmgr/conf/
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
```

- Then I deployed it with `docker-compose start` and accessing to the container, the file with the comment is here:
```
I have no name!@f9c44ca73827:/$ cat /bitnami/postgresql/conf/pg_hba.conf
host     all            repmgr    0.0.0.0/0    md5
host     repmgr         repmgr    0.0.0.0/0    md5
host     replication      repmgr    0.0.0.0/0    md5
#hostssl     all             all             0.0.0.0/0               cert
#hostssl     all             all             ::/0                    cert
host     all              all       0.0.0.0/0    md5
host     all              all       ::/0         md5
local    all              all                    md5
#This is a comment
```

Are you able to reproduce those steps? Please, take into account adding the `BITNAMI_DEBUG=true` env. variable helps to see more information in the logs

**Comment by leonidn22** [comment]
Hi Carlos,

Thank You for reproducing the case.
I did something similar and the file pg_hba.conf was rewritten by the
docker.
I will try it again as You wrote on Sunday and I will write You the results.
Hope it will work.

Thanks,
Leonid.,

11 сент. 2020 г. 11:28 ДП пользователь "Carlos Rodríguez Hernández" <
notifications@github.com> написал:

**Comment by leonidn22** [comment]
Hi,

I manage to keep my pg_hba.conf updated in the following two steps:

1. change in bitnami-docker-postgresql-repmgr/12/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh :

```
repmgr_inject_pghba_configuration() {
    debug "Injecting a new pg_hba.conf file..."
    local tls_auth="#"
    if is_boolean_yes "$POSTGRESQL_ENABLE_TLS" && [[ -n $POSTGRESQL_TLS_CA_FILE ]]; then
        tls_auth=""
    fi
    debug "NOT AND NOT Injecting a new pg_hba.conf file"
#    cat > "${POSTGRESQL_MOUNTED_CONF_DIR}/pg_hba.conf" << EOF
# host     all            $REPMGR_USERNAME    0.0.0.0/0    trust
#host     $REPMGR_DATABASE         $REPMGR_USERNAME    0.0.0.0/0    trust
#host     replication      $REPMGR_USERNAME    0.0.0.0/0    trust
#${tls_auth}hostssl     all             all             0.0.0.0/0               cert
#${tls_auth}hostssl     all             all             ::/0                    cert
#host     all              all       0.0.0.0/0    trust
#host     all              all       ::/0         trust
#local    all              all                    trust
# EOF
}
```

2. change in bitnami-docker-postgresql-repmgr/12/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh

```
postgresql_restrict_pghba() {
    if [[ -n "$POSTGRESQL_PASSWORD" ]]; then
        local pghba_file
#        replace_in_file "$POSTGRESQL_PGHBA_FILE" "trust" "md5" false
    fi
}
```

May be it would be possible changing the default behavior using new variables?

Besides I have to install 

CREATE EXTENSION plpython2u;
CREATE EXTENSION plpython3u; 

Is there plan to add such extensions?


Thanks,
Leonid.,

**Comment by carrodher** [comment]
Hi, I am glad you were able to solve your issue. Regarding those extensions, we don't have a plan to add them pre-installed in the image in the short-term; hope you can install it manually by yourself.

Please, don't hesitate to ask more questions about this topic if needed. Thanks
