### ISSUE TITLE
Install plpython3u extension

### ISSUE THREAD

**Issue by leonidn22** [bitnami/bitnami-docker-postgresql-repmgr#38]
Hi,

To install it I run from docker exec  -it -u root pg-0 /bin/bash :

```
echo 'deb http://ftp.de.debian.org/debian sid main' >> /etc/apt/sources.list
apt-get update && apt-get install mlocate python3 postgresql-plpython3-12

cp -r /usr/lib/postgresql/11/lib/* /opt/bitnami/postgresql/lib/.
cp /usr/share/postgresql/11/extension/pl* /opt/bitnami/postgresql/share/extension/.

```
And finally I got the following error:

postgres=# create extension plpython3u;
ERROR:  could not load library "/opt/bitnami/postgresql/lib/plpython3.so": /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0)

I am not sure if it's possible to fix.
Is any recommendations?

thanks,
Leonid.,

**Comment by javsalgar** [comment]
Hi,

I believe the main cause of the issue is that you are not using the debian buster apt repositories but the debian sid apt repositories. That would explain the glibc incompatibility. Could you try using the `debian buster` apt repositories?

**Comment by leonidn22** [comment]
Hi,

Thank You for the advice.
It lead me to: https://wiki.postgresql.org/wiki/Apt
And it works OKay.
