### ISSUE TITLE
permission denied to create extension "postgis"

### ISSUE THREAD

**Issue by batchenr** [bitnami/bitnami-docker-postgresql-repmgr#4]
Hey,

First of all thank you for adding postgis extension!!!
Im using the image bitnami-docker-postgresql-repmgr:11

I do have an issue with it, as i have an existing database which is copied to /docker-entrypoint-initdb.d , in my sql file i have the "create extension postgis;"

sql file runs when container is up isnt running with the superuser,  
That makes only tables that arnt using postgis extention to be created and all the rest to be discarded, 
1. can please add an error as container goes up ? i didn't noticed any error so it took me some time to understand why not all tables where created.
here is sql file example to duplicate :

```
CREATE EXTENSION postgis;
CREATE TABLE events (
        id SERIAL PRIMARY KEY,
        ts TIMESTAMP NOT NULL DEFAULT NOW(),
        ids text[][],
        type text[][],
        location geometry(POINT),
        info json,
        altitude float
);
CREATE TABLE events_issues (type text);


```
Table events will not be created as the missing postgis for the  "location geometry(POINT),"
and i will not see an error as container goes up, and table events_issues  will be created.

2.To prevent it, can you make .sql files that are in /docker-entrypoint-initdb.d to run as super user ?

if i try manually to create as the user i specified in                 :
`POSTGRESQL_USERNAME=user
`
i get :   

```
ERROR:  permission denied to create extension "postgis"
HINT:  Must be superuser to create this extension.

```
If i change user to postgres it adds the extension.
my dockerfile : 
```
FROM bitnami/postgresql-repmgr:11
COPY /cluster/z_postgres.sql /docker-entrypoint-initdb.d/
```

**Comment by enote-kane** [comment]
In case anyone stumbles upon this, just use the following variables for executing scripts/SQL in `/docker-entrypoint-initdb.d/`:
* `POSTGRESQL_INITSCRIPTS_USERNAME` (should be set to `postgres`)
* `POSTGRESQL_INITSCRIPTS_PASSWORD` (the password for user `postgres`)

For troubleshooting, always start containers with variable `BITNAMI_DEBUG=true`, which helps a lot especially in cases like this.

**Comment by rafariossaa** [comment]
Hi @enote-kane ,
  Thanks for sharing your comments on how to do this.
  @batchenr Could you check if you can use what @enote-kane indicated ?.

**Comment by enote-kane** [comment]
@rafariossaa Any update on this?

**Comment by rafariossaa** [comment]
Hi,
  Could you check if we the current version of the container image, this still happens ?
