### ISSUE TITLE
Node is not attached to its upstream node

### ISSUE THREAD

**Issue by amirbayan** [bitnami/bitnami-docker-postgresql-repmgr#43]
**Description**
I am using this image from docker hub bitnami/postgresql-repmgr:latest. 
I have setup a 3 server to host the cluster (10.100.105.29 - primary, 10.100.105.32 - standby, 10.100.105.28 - standby).
everything is fine and the database is being replicated normally, but when I check cluster status from repmgr I got the below message: 
node "pgrepmgr-1" (ID: 1001) is not attached to its upstream node "pgrepmgr-0" (ID: 1000)
node "pgrepmgr-2" (ID: 1002) is not attached to its upstream node "pgrepmgr-0" (ID: 1000)

I have done too many research but with no result.

**Steps to reproduce the issue:**

1. Setup Primary-Standby cluster with 3 servers ( 3 instances)
2. check cluster info from replication manager: 
docker exec -it container-name /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show

**Describe the results you received:**

node "pgrepmgr-1" (ID: 1001) is not attached to its upstream node "pgrepmgr-0" (ID: 1000)
node "pgrepmgr-2" (ID: 1002) is not attached to its upstream node "pgrepmgr-0" (ID: 1000)

**Describe the results you expected:**

the error message must not be shown in cluster info command (node "pgrepmgr-1" (ID: 1001) is not attached to its upstream node "pgrepmgr-0" (ID: 1000))
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.12, build 48a66213fe
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.19.1.el7.x86_64
 Operating System: Red Hat Enterprise Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.666GiB
 Name: SLB-UATDFGWDB-1.sb-uat.com
 ID: BCHX:O577:D4B4:BQFG:7JJ7:L4XZ:MDBP:6DJJ:WUEQ:PIST:DRDR:BZH6
 Docker Root Dir: /data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  10.100.40.2
  10.100.40.2:8083
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  Thanks for reporting this.
  I was able to reproduce it with different container versions. I checked that the replication is working and promotion of a new primary node occurs. 
  I am creating an internal task to look deeper into this.

  Please, if you notice any issue apart from the messages let us now.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the late answer. 
  This issues was fixed. Could you try the latest version of postgresql-repmgr ?

**Comment by amirbayan** [comment]
hello @rafariossaa ,

I have tried it and it is working as expected. Thank you 🙏

**Comment by rafariossaa** [comment]
Hi,
 Thanks for testing it.
