### ISSUE TITLE
pgRouting

### ISSUE THREAD

**Issue by hyungmok** [bitnami/bitnami-docker-postgresql-repmgr#45]
Hi,

I guess this wouldn't be an issue, but wanted to see if I could get any help from folks.

So my team is using the bitnami-docker-postgresql-repmgr thanks to bitnami team's effort. If I understood correctly, this image contains the replication feature, which is very useful. In addition to the replication feature, we need the feature of pgRouting as well, and it seems like there's already a good image providing the pgRouting feature like docker-pgrouting.

However, the problem is that if we go with the bitnami-docker-postgresql-repmgr, then we can't use the pgRouting feature, in the other case, we can't use the replication feature. So I'm wondering if there's any way to include the pgRouting feature to this container image or if you have any plan to include it.

It would be very helpful if you leave me any comments. Thanks in advance.

/Dave

**Comment by rafariossaa** [comment]
Hi,
 Thank your very much for using our container, we are happy you find it useful.
 Sorry, but unfortunately there are not plans to include pgRouting in the container. We are a small team at this depends on request we receive, tasks priorities, etc.
 Maybe you can create a new image copying the pgrouting files into our container. As they are a different compilation there is not guarantee it will work, but you can give it a try.

**Comment by hyungmoklee** [comment]
> Hi,
> Thank your very much for using our container, we are happy you find it useful.
> Sorry, but unfortunately there are not plans to include pgRouting in the container. We are a small team at this depends on request we receive, tasks priorities, etc.
> Maybe you can create a new image copying the pgrouting files into our container. As they are a different compilation there is not guarantee it will work, but you can give it a try.

Thanks for the quick response! Yeah, that's one option I would consider but it turns out that the directory two containers are using is different from each other. So I'm having a hard time how I could copy things to the bitnami container.

**Comment by rafariossaa** [comment]
Hi,
  Maybe you can use `ldd` to find where you need to copy the files.
  For example, in our container,  `postgis.so` is located in `/opt/bitnami/postgresql/lib` and dependencies are like:
```
...
        libgeos_c.so.1 => /opt/bitnami/postgresql/lib/libgeos_c.so.1 (0x00007f8e99f3b000)
        libproj.so.15 => /opt/bitnami/postgresql/lib/libproj.so.15 (0x00007f8e99c7f000)
        libjson-c.so.4 => /opt/bitnami/postgresql/lib/libjson-c.so.4 (0x00007f8e99c6a000)
...
```
  I hope this helps.
