### ISSUE TITLE
node name not found

### ISSUE THREAD

**Issue by hey-hoho** [bitnami/bitnami-docker-postgresql-repmgr#46]
this is error logs:

```
postgresql-repmgr 08:09:39.73 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **

repmgr 08:09:39.85 INFO  ==> Validating settings in REPMGR_* env vars...

repmgr 08:09:39.85 ERROR ==> The node name does not follow the required format. Valid format: ^.*+-[0-9]+$

/librepmgr.sh: line 118: $(MY_POD_NAME): syntax error: operand expected (error token is "$(MY_POD_NAME)")

repmgr 08:09:39.86 ERROR ==> The node id is required. Set the environment variable REPMGR_NODE_ID with the node id.

```

I use this helm chart to deploy:
https://github.com/helm/charts/tree/master/stable/postgresql

**Comment by dani8art** [comment]
Hi @hey-hoho we already deprecated this chart in favor of https://github.com/bitnami/charts/tree/master/bitnami/postgresql, please could you give it a try?

**Comment by hey-hoho** [comment]
Hi @dani8art , I'm glad to try it, Thanks very much!

**Comment by gotiniens** [comment]
For future reference, I ran into the same problem. I was able to fix this by removing the app (I use rancher), and reinstall the chart with the same answers.yml

@dani8art Do you mean the postgresql-repmgr chart is not supported anymore? Could that be communicated a bit more clearly? For example the postgresql-ha chart still uses the postgresql-repmgr by default. Also the documentation for the pgpool-II docker container still references postgresql-repmgr in their example.

**Comment by dani8art** [comment]
Hi @gotiniens, 

No, I meant `stable/postgresql` is deprecated as he was pointing to it

> I use this helm chart to deploy: https://github.com/helm/charts/tree/master/stable/postgresql

We will be maintaining both `bitnami/postgresql` and `bitnami/postgresql-ha`.

**Comment by quaredevil** [comment]
###Same problem:

I noticed that this issue sometimes happens when restarting the pods.

`FROM bitnami/postgresql-repmgr:13`

```postgresql-repmgr 20:56:45.49 
postgresql-repmgr 20:56:45.49 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 20:56:45.50 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 20:56:45.50 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 20:56:45.50 
postgresql-repmgr 20:56:45.53 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 20:56:45.56 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 20:56:45.56 ERROR ==> The node name does not follow the required format. Valid format: ^.*+-[0-9]+$
/opt/bitnami/scripts/librepmgr.sh: line 31: $(MY_POD_NAME): syntax error: operand expected (error token is "$(MY_POD_NAME)")
postgresql-repmgr 20:56:45.57 ERROR ==> The node id is required. Set the environment variable REPMGR_NODE_ID with the node id.```

**Comment by juan131** [comment]
@quaredevil please open an issue at https://github.com/helm/charts/issues if you're using the Bitnami PostgreSQL HA chart describing how to reproduce the issue. Thanks in advance.
