### ISSUE TITLE
Use existing data directory in standby node and only sync differences from primary node?

### ISSUE THREAD

**Issue by hi-usui** [bitnami/bitnami-docker-postgresql-repmgr#49]
Related to https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/20#issuecomment-628136431

Currently, even if the entire data directory is cloned from a primary node, the standby node *always* deletes the data directory and clones data from the primary node. It also happens even every time the node restarts.

How can we use the existing data directory or disable the force option?

![Screen Shot 2020-10-24 at 15 25 45](https://user-images.githubusercontent.com/22272118/97094840-9ed3d200-160d-11eb-928f-c6fa93b8853a.png)

```
postgresql-repmgr 22:23:54.36
postgresql-repmgr 22:23:54.36 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 22:23:54.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 22:23:54.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 22:23:54.37
postgresql-repmgr 22:23:54.40 DEBUG ==> Configuring libnss_wrapper...
postgresql-repmgr 22:23:54.48 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 22:23:54.59 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 22:23:54.60 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 22:23:54.62 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 22:23:54.70 DEBUG ==> Checking node 'berkeleytime-psql-postgresql-ha-postgresql-0.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'...
postgresql-repmgr 22:23:54.88 DEBUG ==> Pretending primary role node - 'berkeleytime-psql-postgresql-ha-postgresql-0.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'
postgresql-repmgr 22:23:54.88 DEBUG ==> Pretending primary set to 'berkeleytime-psql-postgresql-ha-postgresql-0.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'!
postgresql-repmgr 22:23:54.89 DEBUG ==> Checking node 'berkeleytime-psql-postgresql-ha-postgresql-1.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'...
psql: error: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "berkeleytime-psql-postgresql-ha-postgresql-1.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local" (10.244.184.214) and accepting
        TCP/IP connections on port 5432?
postgresql-repmgr 22:23:54.91 DEBUG ==> Skipping: failed to get primary from the node 'berkeleytime-psql-postgresql-ha-postgresql-1.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'!
postgresql-repmgr 22:23:54.91 INFO  ==> Auto-detected primary node: 'berkeleytime-psql-postgresql-ha-postgresql-0.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'
postgresql-repmgr 22:23:54.91 DEBUG ==> Primary node: 'berkeleytime-psql-postgresql-ha-postgresql-0.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'
postgresql-repmgr 22:23:54.93 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 22:23:54.95 DEBUG ==> Injecting a new postgresql.conf file...
postgresql-repmgr 22:23:54.96 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 22:23:55.08 DEBUG ==> Injecting a new pg_hba.conf file...
postgresql-repmgr 22:23:55.09 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 22:23:55.10 DEBUG ==> Node ID: '1001', Rol: 'standby', Primary Node: 'berkeleytime-psql-postgresql-ha-postgresql-0.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432'
postgresql-repmgr 22:23:55.11 INFO  ==> Initializing Repmgr...
postgresql-repmgr 22:23:55.13 INFO  ==> Waiting for primary node...
postgresql-repmgr 22:23:55.13 DEBUG ==> Wait for schema repmgr.repmgr on 'berkeleytime-psql-postgresql-ha-postgresql-0.berkeleytime-psql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432', will try 6 times with 10 delay seconds (TIMEOUT=60)
postgresql-repmgr 22:23:55.16 DEBUG ==> Schema repmgr.repmgr exists!
postgresql-repmgr 22:23:55.17 INFO  ==> Cloning data from primary node...
WARNING: following problems with command line parameters detected:
  -D/--pgdata will be ignored if a repmgr configuration file is provided
NOTICE: destination directory "/bitnami/postgresql/data" provided
NOTICE: checking for available walsenders on the source node (2 required)
NOTICE: checking replication connections can be made to the source server (2 required)
WARNING: data checksums are not enabled and "wal_log_hints" is "off"
DETAIL: pg_rewind requires "wal_log_hints" to be enabled
WARNING: directory "/bitnami/postgresql/data" exists but is not empty
NOTICE: deleting existing directory "/bitnami/postgresql/data"
NOTICE: starting backup (using pg_basebackup)...
```

**Comment by dani8art** [comment]
Hi @uberkelium currently we are using repmgr to handle replication in our postgresql instance using the [clone command](https://repmgr.org/docs/5.2/repmgr-standby-clone.html) this command needs an empty directory where to store the data, also we use performance-related flags like `--fast-checkpoint` as recommended by the [advanced clone options](https://repmgr.org/docs/4.0/cloning-advanced.html)

https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/8652180f760feee8c8028fac5faedbc993df3829/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L473-L478

Anyway, we are open to any suggestions if you consider or find another way of doing it.

**Comment by uberkelium** [comment]
> Hi @uberkelium currently we are using repmgr to handle replication in our postgresql instance using the [clone command](https://repmgr.org/docs/5.2/repmgr-standby-clone.html) this command needs an empty directory where to store the data, also we use performance-related flags like `--fast-checkpoint` as recommended by the [advanced clone options](https://repmgr.org/docs/4.0/cloning-advanced.html)
> 
> https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/8652180f760feee8c8028fac5faedbc993df3829/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L473-L478
> 
> Anyway, we are open to any suggestions if you consider or find another way of doing it.

@dani8art Thank you for responding with the links. After reading these resources and your post, I still do not understand how to achieve what I am trying to do: Use the existing data directory and sync the differences only. I am a bit inexperienced with PostgreSQL replication, so can you explain what I can do regarding "repmpgr standby clone" alternatives? From what I understand, "repmgr standby clone" always needs an empty directory, but because of "--force" option, it deletes the existing data. So is there a replication method for repmgr that allows replication without deleting all the old data?

Primary node: Copy all the files to secondary nodes
Secondary node: Start up Postgres, realize that existing data is nearly identical to primary, sync differences, begin streaming, do not do a full copy

**Comment by dani8art** [comment]
> "repmgr standby clone" always needs an empty directory, but because of "--force" option, it deletes the existing data

Yes, that's correct and if you keep data and remove the flag "--force" the clone action fails

> So is there a replication method for repmgr that allows replication without deleting all the old data?

We also tried to use `repmgr node rejoin` with `--force-rewind` flag, without success. 

As my colleague posted on this other issue https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/20#issuecomment-716563032, cloning would not be the better option for large database but would be the a way that will work in any environment.
