### ISSUE TITLE
repmgr switchover does not work because SSH keys aren't set up

### ISSUE THREAD

**Issue by psrcek** [bitnami/bitnami-docker-postgresql-repmgr#51]
**Description**

I cannot run repmgr switchover because the containers do not have SSH set up properly.

The command I'm running is: `docker exec -it postgresql /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf standby switchover`

**Steps to reproduce the issue:**

1. Start up two containers with replication with the help of the README.
2. Run the above command
3. Observe the below error

**Describe the results you received:**

I get the following output:
```
NOTICE: executing switchover on node "pg-1" (ID: 2)
WARNING: unable to connect to remote host "pg-0" via SSH
ERROR: unable to connect via SSH to host "pg-0", user ""
```

**Describe the results you expected:**

I expected my nodes to switchover correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 42
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 188.8GiB
 Name: venus00
 ID: OJSS:QMKD:CXOV:R5VD:2ESY:RCJC:5KZR:K5ML:K2K4:L2OC:VCQZ:MOM3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Nothing special, just running the containers on two physical machines. Wouldn't work on one machine either.

**Comment by andresbono** [comment]
Hi @psrcek, it is not a common practice to use ssh and ssh keys to communicate between nodes in a container environment. In any case, you may want to customize the container to install ssh and mount the ssh key files in the different containers.

**Comment by psrcek** [comment]
Well I know that's a non standard way of communicating between them, but repmgr uses it to run commands on other machines so it can stop postgres and change stuff around to do a switchover. I don't want to customize anything here, I just want to use a standard feature of repmgr. (switchover)

**Comment by andresbono** [comment]
I understand but the main purpose of this container image is to be used in the chart [bitnami/postgresql-ha](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha). I can't tell you if we are going to add ssh by default in the short term.

In order to support different use cases like yours, we allow our containers to be extended to meet different user needs. We can help you with that as well if needed.

**Comment by psrcek** [comment]
Please do as I don't even know where to start adding the SSH keys. In fact, I don't even know what non-root user the services are running as, I've checked /etc/passwd but can't seem to be able to locate it

**Comment by andresbono** [comment]
Hi @psrcek, we have started checking possible ways of customizing the container to enable standby switchover. We couldn't make it work. So far, this is what we have:

```Dockerfile
FROM bitnami/postgresql-repmgr:11

USER root
RUN install_packages ssh net-tools vim
RUN mkdir -p /run/sshd /ssh && \
    chown -R 1001 /etc/ssh /ssh && \
    echo 'AuthorizedKeysFile /ssh/authorized_keys' >>/etc/ssh/sshd_config && \
    echo 'Host pg-*' >>/etc/ssh/ssh_config && \
    echo '    Port 22022' >>/etc/ssh/ssh_config && \
    echo '    User 1001' >>/etc/ssh/ssh_config && \
    echo '    IdentityFile /ssh/id_rsa' >>/etc/ssh/ssh_config

USER 1001

CMD [ "bash", "-c", "/usr/sbin/sshd -p 22022 && /opt/bitnami/scripts/postgresql-repmgr/run.sh" ]
```

Then, you mount private/public ssh keys into `/ssh`, i.e:

```
      - './id_rsa:/ssh/id_rsa'
      - './id_rsa.pub:/ssh/authorized_keys'
```

Please check it on your side in case it helps to getting closer to a solution for your issue.

**Comment by sbJonas** [comment]
Hi,
i tried @andresbono´s approach and after many tries and errors i got the switchover command working. I am definitely not an expert in docker, so this could be improved i guess. So here are the steps to reproduce my workaround:
Create a standard OpenSSH sshd_config file with following changes:
```
Port 22022
LogLevel DEBUG
AuthorizedKeysFile /etc/ssh/authorized_keys
PasswordAuthentication no
UsePAM no
PermitUserEnvironment yes
PidFile /etc/ssh/sshd.pid
```

Create the Dockerfile:
```
FROM docker.io/bitnami/postgresql-repmgr:10
ENV PYTHONUNBUFFERED 1

USER root
RUN apt-get update -y && apt-get upgrade -y
# added python for python repmgr event scripts
RUN apt-get install python3 python3-pip openssh-server -y
RUN pip3 install requests

# prevent container crash due "cat: /opt/bitnami/postgresql/conf/pg_hba.conf: No such file or directory"
COPY ./pgconf/pg_hba.conf /opt/bitnami/postgresql/conf/pg_hba.conf

# Setup ssh
# required for privilege separation
RUN mkdir -p /run/sshd
COPY ./sshd_config /etc/ssh/sshd_config
RUN ssh-keygen -A

# required for ssh
RUN mkdir -p /home/pgrepmgruser
# required for switchover
RUN touch /home/pgrepmgruser/.profile
RUN echo 'export PATH="/opt/bitnami/postgresql/bin:/opt/bitnami/repmgr/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"' >> /home/pgrepmgruser/.profile
RUN groupadd --gid 1001 pgrepmgruser && useradd --uid 1001 --gid 1001 -d /home/pgrepmgruser -p '*' -s /bin/bash pgrepmgruser
# Links for switchover commands
RUN ln -s /bitnami/repmgr/conf/repmgr.conf /etc/repmgr.conf
RUN ln -s /opt/bitnami/repmgr/bin/repmgr /opt/bitnami/postgresql/bin/repmgr

RUN chown -R pgrepmgruser /home/pgrepmgruser /etc/ssh /opt/bitnami

USER pgrepmgruser
ENTRYPOINT [ "/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh" ]
# Useful for debugging ssh, does not start repmgr
#CMD [ "bash", "-c", "/usr/sbin/sshd -D -e" ]
CMD [ "bash", "-c", "/usr/sbin/sshd && /opt/bitnami/scripts/postgresql-repmgr/run.sh" ]
```

Create 2 ssh keys (id_rsa and id_rsa2 in my example)
Create 2 empty files for known host entries (known_hosts and known_hosts2)
Create 2 ssh_config files (ssh_config and ssh_config2) with following content (replace server 2 ip in ssh_config and server 1 ip in ssh_config2)
```
Host xx.xx.xx.xx
  Hostname xx.xx.xx.xx
  user pgrepmgruser
  Port 22022
  PubKeyAuthentication yes
  IdentityFile /etc/ssh/id_rsa_ssh_client
  UserKnownHostsFile /etc/ssh/known_hosts
```
Then finally the docker-compose.yml files with following volumes can be created (at least some files have to be owned by 1001:1001 on the hosts):
server 1
```
- ./id_rsa:/etc/ssh/id_rsa_ssh_client
- ./id_rsa2.pub:/etc/ssh/authorized_keys
- ./ssh_config:/etc/ssh/ssh_config
- ./known_hosts:/etc/ssh/known_hosts
```
server 2
```
- ./id_rsa2:/etc/ssh/id_rsa_ssh_client
- ./id_rsa.pub:/etc/ssh/authorized_keys
- ./ssh_config2:/etc/ssh/ssh_config
- ./known_hosts2:/etc/ssh/known_hosts
```
Then log into both containers and try the ssh connection via "ssh xx.xx.xx.xx" and enter yes to accept the connection and create the entries in the known_hosts files. After that repmgr standby switchover worked for me.

**Comment by miguelaeh** [comment]
Hi @sbJonas ,
Thank you very much for sharing your solution!! It will definitely be useful for other users that want to extend our container to support that.
