### ISSUE TITLE
Change repmgr password

### ISSUE THREAD

**Issue by TamarNR** [bitnami/bitnami-docker-postgresql-repmgr#55]
Hi,

I needed to change my superuser password.
I did that for both primary and standby like this:
On the postgres level I changed it usoing the comamnd /password from psql.
For the repmgr/bitnami level, I changed the conninfo in repmgr.conf.

However "select * from nodes" still shows the old password.

Is there somewhere else to change the password?

Thanks,
Tamar

**Comment by TamarNR** [comment]
I posted the question in repmgr forum, and was told do do this:

"To update the repmgr metadata, you'll need to run:

    repmgr primary register --force

or

    repmgr standby register --force

on each node as appropriate.

To update the password used for replication, you'll need to run:

    repmgr standby clone --replication-conf-only

on each standby; for details see:

    https://repmgr.org/docs/current/repmgr-standby-clone.html#REPMGR-STANDBY-CREATE-RECOVERY-CONF
and restart the standby (PostgreSQL 13: reload configuration)."

But how do I perform the clone part with bitnami repmgr?

Thanks, Tamar

**Comment by juan131** [comment]
Hi @TamarNR 

You can set a custom password for `repmgr` using the `REPMGR_PASSWORD` environment variable as described in the link below:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr#setting-the-root-and-repmgr-passwords-on-first-run

> Please note that these environment variables will be only taking into account during the 1st boot of the container. They will be ignored during container restarts, and you'll have to manually change them in case you want to update them.

**Comment by TamarNR** [comment]
Hi Juan,

Thanks for the info.

Apparently just using:
$ docker exec -ti <container name>  /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf primary register --force

updated both the primary and the running (but unreachable up to this point) standby with the new password.

A question though regarding the password security:
repmgr documentation specifies that the most secure way is to store the password is in the password file ~/.pgpass
https://repmgr.org/docs/current/configuration-password-management.html

Does the repmgr container supports this? 

As far as we could see setting these environment variables of docker run command:
  --env REPMGR_PASSWORD=mypassword
  --env POSTGRESQL_PASSWORD=mypassword

will cause the repmgr.conf to store the password in the conninfo information.

Is there a way to avoid this?

Thanks,
Tamar

**Comment by juan131** [comment]
Hi @TamarNR 

As you can see in the link below:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L259

We use `REPMGR_PASSWORD` to directly create the repmgr user in the PostgreSQL database running a SQL command. Currently this image doesn't support any alternative to do so.

The password is also added to **/opt/bitnami/repmgr/conf/repmgr.conf** as part of the `promote_command` and `follow_command` to use, see:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L398

**Comment by TamarNR** [comment]
Thanks
