### ISSUE TITLE
Change to postgresql.conf in order to log slow queries 

### ISSUE THREAD

**Issue by TamarNR** [bitnami/bitnami-docker-postgresql-repmgr#57]
Hi,

I am trying to change postgresql.conf  to log slow queries.
I put the follwoing parameters in postgresql.conf :
```
log_directory = 'pg_log'
logging_collector = on
log_min_duration_statement = 20
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_statement = 'all'
log_min_error_statement = error
log_line_prefix = '%t [%p]: [%l-1] '
log_autovacuum_min_duration = 0
```
But I can see no result in docker logs for the container.

I can see that the changes were reloaded into postgres:
```
# show log_min_duration_statement ;
 log_min_duration_statement
----------------------------
 20ms
(1 row)

# show log_connections;
 log_connections
-----------------
 on
(1 row)

still 'log_directory' shows the default log:
# show log_directory;
        log_directory
------------------------------
 /opt/bitnami/postgresql/logs
(1 row)

$ cd /opt/bitnami/postgresql/logs
I have no name!@a8b1a5ec5c5e:/opt/bitnami/postgresql/logs$ ls -l
total 0
lrwxrwxrwx 1 root root 11 Jul 15 22:42 postgresql.log -> /dev/stdout
```
but, as noted before, nothing is written into the docker logs.

How can I produce a log then with all the queries?

Thanks,
Tamar

**Comment by carrodher** [comment]
Are you mounting the configuration file from your host or editing the existing one from inside the container? In the first case, everything should work as the configuration file is used since the beginning with your custom configuration. In the second case, the configuration file was edited and you can check with the postgresql client the new values because the file contains them, but maybe as postgresql was not executed with that configuration file since the beginning the changes are not being taken into account.

The proper way to use a custom configuration file and persist it between different executions is to follow the approach described in the following link https://github.com/bitnami/bitnami-docker-postgresql-repmgr#configuration-file

Apart from that, if the configuration file is properly being used by postgresql I can't see any issue with the container itself. Can you double-check if the customization of those parameters is going to solve your use case?

**Comment by TamarNR** [comment]
Hi Carlos,

Yes, the confoiguration file is monted as a volume, and I stop and start the container after the change to the parameters.
Here is the docker inspect of the  container:
[
    {
        "Id": "54901531dca9806e4c101a19ed4503003b05e1db0660404be7cdb8b38fe54901",
        "Created": "2020-11-24T10:34:43.472549552Z",
        "Path": "/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh",
        "Args": [
            "/opt/bitnami/scripts/postgresql-repmgr/run.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 58463,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-11-24T10:34:44.503534591Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:db9fe56fb939c87d10a71037e02be0e9e6a58d808ab6385e23e40a791f80ab47",
        "ResolvConfPath": "/var/lib/docker/containers/54901531dca9806e4c101a19ed4503003b05e1db0660404be7cdb8b38fe54901/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/54901531dca9806e4c101a19ed4503003b05e1db0660404be7cdb8b38fe54901/hostname",
        "HostsPath": "/var/lib/docker/containers/54901531dca9806e4c101a19ed4503003b05e1db0660404be7cdb8b38fe54901/hosts",
        "LogPath": "/var/lib/docker/containers/54901531dca9806e4c101a19ed4503003b05e1db0660404be7cdb8b38fe54901/54901531dca9806e4c101a19ed4503003b05e1db0660404be7cdb8b38fe54901-json.log",
        "Name": "/oct-postgres-mek-13",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/oct/mek-13/config/postgres/postgresql.conf:/bitnami/repmgr/conf/postgresql.conf:rw",
                "/oct/mek-13/postgresql/data:/bitnami/postgresql/data:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "5432/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5013"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 1073741824,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "Init": false
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/f1cc2da737b3102ed140f6668211f152b2cd7c722f933a0799e9684e457fd8e6-init/diff:/var/lib/docker/overlay2/74abfef94c4c8933b4538c7b0a0ad3fc9854e59f02713bf65821cb22526948ad/diff:/var/lib/docker/overlay2/d7e5c21e5e1b289d1fcf3d0302a0c993c631a1a215cd2139159c2d27e908680f/diff:/var/lib/docker/overlay2/81630b8a7e0f4f485b80976efcea1d1c1d8b212fcfccd980e20a6718a8e66b25/diff:/var/lib/docker/overlay2/b9ecc9818b77e0b2c2a0835bb4ff0f1e912eaa4afa155548189b539eb186f35e/diff:/var/lib/docker/overlay2/8cff00d7b164e3bb5b76e47de8adaa47297431798eefb066139f06edf90a6d63/diff:/var/lib/docker/overlay2/1e48be655bfa66deb72cf45616a2276ab7fb35111ef18c1835de8077540a2399/diff:/var/lib/docker/overlay2/4557af506c482ef16e2aaae7cbf1e7eb086c14d27c63e729ed5608aa35e4f741/diff:/var/lib/docker/overlay2/6fefb5265ad25534eddc0bd64f703d1e95c6c4205e3ac08f21566d3390c2358a/diff:/var/lib/docker/overlay2/c2b00e37f1176a91bdf6bdbde87f0df3f23fbab7c0c66b4799f3b8beb4a2ba61/diff:/var/lib/docker/overlay2/741a3d786270617cdb7997f6e1c23a5fe75a62e693b59c378f607a2d45131733/diff:/var/lib/docker/overlay2/cb25984c5d5f52f42eda8c8541b97c72253f3857c3b3d6b67009b1cba0500633/diff:/var/lib/docker/overlay2/e64086bedbc924ed4e4bf58f86512781c71d0e89be6895a421b18c3f17682aba/diff:/var/lib/docker/overlay2/b853ae1988ff913d2c7e10f7a59a673b67bb327389704dccd1243264bfa00c5e/diff",
                "MergedDir": "/var/lib/docker/overlay2/f1cc2da737b3102ed140f6668211f152b2cd7c722f933a0799e9684e457fd8e6/merged",
                "UpperDir": "/var/lib/docker/overlay2/f1cc2da737b3102ed140f6668211f152b2cd7c722f933a0799e9684e457fd8e6/diff",
                "WorkDir": "/var/lib/docker/overlay2/f1cc2da737b3102ed140f6668211f152b2cd7c722f933a0799e9684e457fd8e6/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/oct/mek-13/config/postgres/postgresql.conf",
                "Destination": "/bitnami/repmgr/conf/postgresql.conf",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/oct/mek-13/postgresql/data",
                "Destination": "/bitnami/postgresql/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "54901531dca9",
            "Domainname": "",
            "User": "1001",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "REPMGR_PARTNER_NODES=x.x.7.150,x.x.7.97",
                "REPMGR_PASSWORD=mypassword",
                "REPMGR_PORT_NUMBER=5013",
                "POSTGRESQL_USERNAME=oct",
                "REPMGR_PRIMARY_PORT=5013",
                "POSTGRESQL_PASSWORD=mypassword",
                "REPMGR_NODE_NETWORK_NAME=x.x.7.150",
                "REPMGR_PRIMARY_HOST=x.x.7.150",
                "POSTGRESQL_PORT_NUMBER=5432",
                "POSTGRESQL_POSTGRES_PASSWORD=mypassword",
                "TZ=IST-+2",
                "REPMGR_LOG_LEVEL=DEBUG",
                "POSTGRESQL_DATABASE=xxxdb",
                "REPMGR_NODE_NAME=octpg-0",
                "REPMGR_USERNAME=octrepmgr",
                "PATH=/opt/bitnami/postgresql/bin:/opt/bitnami/repmgr/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/",
                "OS_ARCH=amd64",
                "OS_FLAVOUR=debian-10",
                "OS_NAME=linux",
                "BITNAMI_APP_NAME=postgresql-repmgr",
                "BITNAMI_IMAGE_VERSION=11.8.0-debian-10-r53",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "NSS_WRAPPER_LIB=/opt/bitnami/common/lib/libnss_wrapper.so"
            ],
            "Cmd": [
                "/opt/bitnami/scripts/postgresql-repmgr/run.sh"
            ],
            "Image": "bitnami/postgresql-repmgr:11.8.0-debian-10-r53",
            "Volumes": {
                "/bitnami/postgresql/data": {},
                "/bitnami/repmgr/conf/postgresql.conf": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Bitnami <containers@bitnami.com>"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e76195fd846d4cf0bbb6e4abb10109a28af0fc6d1a45d89767a2c5f936e255ad",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5432/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5013"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/e76195fd846d",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "8555cfa67b8e2242588e96c56b97d3adb579b690e61ea45d4376566b93253ea6",
            "Gateway": "x.x.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "x.x.0.8",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:08",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "32d8edae3f87a9390f346aad2fee02e49c32188db5fa3232ec495021ca1c7e2a",
                    "EndpointID": "8555cfa67b8e2242588e96c56b97d3adb579b690e61ea45d4376566b93253ea6",
                    "Gateway": "x.x.0.1",
                    "IPAddress": "x.x.0.8",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:08",
                    "DriverOpts": null
                },
                "oct-mek-13": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "54901531dca9"
                    ],
                    "NetworkID": "d232ac52df26159b656696142304e903447c3a5e1bd238869f3600a6b4612184",
                    "EndpointID": "7c20ac7c9e7b31030c73df5f8b8784775738c0deefcdeed7a71717e82d7ba76a",
                    "Gateway": "x.x.80.1",
                    "IPAddress": "x.x.80.3",
                    "IPPrefixLen": 20,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:c0:a8:50:03",
                    "DriverOpts": null
                }
            }
        }
    }
]


Still not working...
What am I missing?

Thanks,
Tamar

**Comment by carrodher** [comment]
It seems the configuration file you are mounting in the volume is used properly by PostgreSQL as you are able to obtain the values when using the postgresql client.

So assuming the configuration file is properly set, what is the result you should obtain but you're not obtaining? What use case do you want to solve and what guide/doc are you following to set those parameters?

**Comment by TamarNR** [comment]
.
