### ISSUE TITLE
Use README.md example with a specific version, like bitnami/postgresql-repmgr:12/13, pg-1 exited with code 23

### ISSUE THREAD

**Issue by thomas-reinhold-de** [bitnami/bitnami-docker-postgresql-repmgr#61]
**Description**
➜  ~ docker run --name pg-1 \
--network pg-ha-nwk \
--env REPMGR_PARTNER_NODES=pg-0,pg-1 \
--env REPMGR_NODE_NAME=pg-1 \
--env REPMGR_NODE_NETWORK_NAME=pg-1 \
--env REPMGR_PRIMARY_HOST=pg-0 \
--env REPMGR_PASSWORD=repmgrpass \
--env REPMGR_PASSWORD=repmgrpass \
--env POSTGRESQL_POSTGRES_PASSWORD=postgres \
--env POSTGRESQL_USERNAME=customuser \
--env POSTGRESQL_PASSWORD=custompassword \
--env POSTGRESQL_DATABASE=customdatabase \
bitnami/postgresql-repmgr:12
postgresql-repmgr 08:54:11.77
postgresql-repmgr 08:54:11.77 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 08:54:11.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 08:54:11.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 08:54:11.78
postgresql-repmgr 08:54:11.80 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 08:54:11.82 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 08:54:11.83 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 08:54:11.84 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 08:54:11.90 INFO  ==> Auto-detected primary node: 'pg-0:5432'
postgresql-repmgr 08:54:11.91 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 08:54:11.92 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 08:54:12.02 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 08:54:12.02 INFO  ==> Initializing Repmgr...
postgresql-repmgr 08:54:12.03 INFO  ==> Waiting for primary node...
postgresql-repmgr 08:54:12.06 INFO  ==> Cloning data from primary node...
postgresql-repmgr 08:54:13.71 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 08:54:13.71 INFO  ==> Cleaning stale /bitnami/postgresql/data/standby.signal file
postgresql-repmgr 08:54:13.72 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 08:54:13.73 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 08:54:13.75 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 08:54:13.79 INFO  ==> Configuring replication parameters
postgresql-repmgr 08:54:13.83 INFO  ==> Configuring fsync
postgresql-repmgr 08:54:13.85 INFO  ==> Setting up streaming replication slave...
postgresql-repmgr 08:54:13.89 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 08:54:14.12 INFO  ==> Unregistering standby node...
postgresql-repmgr 08:54:14.20 INFO  ==> Registering Standby node...
postgresql-repmgr 08:54:14.25 INFO  ==> Running standby follow...
postgresql-repmgr 08:54:14.32 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped

**Version**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Docker Info**

```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.39-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.807GiB
 Name: docker-desktop
 ID: PGO4:LJ33:AREF:D46R:XWVZ:CRWP:VWCH:FDAM:JI7Q:2DDH:FRRM:QDUA
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 51
  Goroutines: 62
  System Time: 2020-12-01T08:58:17.2001328Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Docker-compose**

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional Info**
```
MacOS 10.15.7
```

**Comment by thomas-reinhold-de** [comment]
I just run the example which provided in the README.md file. There is nothing changed. I found that it worked for version 11, but version 12/13. I think there maybe something wrong with configuration?

**Comment by thomas-reinhold-de** [comment]
Reproduce Steps:
1. Use README.md file example, but with bitnami/postgresql-repmgr:12/13.
2. Run docker-compose up

Error:
pg-1 exited with code 23

Note:
This issue will never appear with version 11.

**Comment by thomas-reinhold-de** [comment]
I retried again. It is not an issue. I should use `postgresql-repmgr:12/13-debian-10`.

**Comment by rafariossaa** [comment]
Hi,  
 Thank you for coming back and sharing your findings.
