### ISSUE TITLE
Question:is it possible to start a standby cluster?

### ISSUE THREAD

**Issue by adacaccia** [bitnami/bitnami-docker-postgresql-repmgr#62]
**Description**
I'd like to start a new postgres cluster as a "standby cluster", meaning it should start over a freshly taken pg_basebackup from and old cluster, and then start streaming as a replica, thus allowing for easy migration / adoption from existing clusters.

**Comment by javsalgar** [comment]
Hi,

I'm not sure how this would be configured. I imagine that the primary should be a replica of one of the other nodes of the clusters. Right now the only way that comes to mind is to use the postgresql init scripts feature to change the configuration of the primary node.
