### ISSUE TITLE
node "octopuspg-1" (ID: 1001) is not attached to its upstream node "octopuspg-0" (ID: 1000)

### ISSUE THREAD

**Issue by TamarNR** [bitnami/bitnami-docker-postgresql-repmgr#65]
Hi,

I see this warning in "cluster show" output, but I am not sure what does it mean as replication and failover seem to work OK:

ID   | Name        | Role    | Status    | Upstream      | Location | Prio. | TLI
------+-------------+---------+-----------+---------------+----------+-------+-----
 1000 | octopuspg-0 | primary | * running |               | default  | 100   | 1
 1001 | octopuspg-1 | standby |   running | ! octopuspg-0 | default  | 100   | 1

WARNING: following issues were detected
  - node "octopuspg-1" (ID: 1001) is not attached to its upstream node "octopuspg-0" (ID: 1000)

repmgr=# select * from pg_stat_replication;
-[ RECORD 1 ]----+------------------------------
pid              | 290
usesysid         | 16386
usename          | octopusrepmgr
application_name | walreceiver
client_addr      | 10.97.7.97
client_hostname  |
client_port      | 58608
backend_start    | 2021-01-11 19:58:18.040158+02
backend_xmin     |
state            | streaming
sent_lsn         | 0/50008B8
write_lsn        | 0/50008B8
flush_lsn        | 0/50008B8
replay_lsn       | 0/50008B8
write_lag        |
flush_lag        |
replay_lag       |
sync_priority    | 0
sync_state       | async

node check on primary:
--------------------------
ostgresql-repmgr 12:04:34.26
postgresql-repmgr 12:04:34.26 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 12:04:34.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 12:04:34.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 12:04:34.27

Node "octopuspg-0":
        Server role: OK (node is primary)
        Replication lag: OK (N/A - node is primary)
        WAL archiving: OK (0 pending archive ready files)
        Upstream connection: OK (N/A - node is primary)
        Downstream servers: CRITICAL (1 of 1 downstream nodes not attached; missing: octopuspg-1 (ID: 1001))
        Replication slots: CRITICAL (1 of 1 physical replication slots are inactive)
        Missing physical replication slots: OK (node has no missing physical replication slots)
        Configured data directory: OK (configured "data_directory" is "/bitnami/postgresql/data")

node check on standby:
-------------------------
Node "octopuspg-1":
        Server role: OK (node is standby)
        Replication lag: OK (0 seconds)
        WAL archiving: OK (0 pending archive ready files)
        Upstream connection: CRITICAL (node "octopuspg-1" (ID: 1001) is not attached to expected upstream node "octopuspg-0" (ID: 1000))
        Downstream servers: OK (this node has no downstream nodes)
        Replication slots: OK (node has no physical replication slots)
        Missing physical replication slots: OK (node has no missing physical replication slots)
        Configured data directory: OK (configured "data_directory" is "/bitnami/postgresql/data")

Is my configuration missing something?

Thanks,
Tamar

**Comment by dani8art** [comment]
Hi, this issue is pretty similar to https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/52, Could you take a look at it, please?

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate which image version are you using ? I tried with latest version `bitnami/postgresql-repmgr:11.10.0-debian-10-r64`. Also, if there are other steps involved or if you just did `docker-compose up`

**Comment by TamarNR** [comment]
Hi,

Problem indeed solved by using newer image bitnami/postgresql-repmgr:11.10.0-debian-10-r64

Thanks
