### ISSUE TITLE
Can we implement this from different machines?

### ISSUE THREAD

**Issue by Thangamh** [bitnami/bitnami-docker-postgresql-repmgr#67]
Can we implement this solution from different servers, without using docker networks.
example: primary node: 10.10.10.10
                secondary node 1: 10.10.10.11
                secondary node 2: 10.10.10.12

Is there any blogs/articles for me to implement this solution for above mentioned architecture?

**Comment by javsalgar** [comment]
Hi,

For use cases that are closer to production, our advice would be using our helm chart in Kubernetes. Did you give it a try?

**Comment by Thangamh** [comment]
Hi @javsalgar , No I havnt came across the helm chart, Can you post the link here please

**Comment by javsalgar** [comment]
Hi,

This is the link to the chart: https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
