### ISSUE TITLE
Cannot run container as root

### ISSUE THREAD

**Issue by hedleyroos** [bitnami/bitnami-docker-postgresql-repmgr#72]
**Description**

Bitnami images can normally be run as root, but not this particular one. The reason for needing to run as root is to enable traffic control on the container so Postgres doesn't saturate the overlay network when eg. a new database is imported. Replicating a few GB between nodes consumes all available IO.

**Steps to reproduce the issue:**

1. Set `user: root` in the docker compose file.
2. Start the stack as per the readme.

**Describe the results you received:**
`/bin/sh: 1: cannot create /opt/bitnami/postgresql/logs/postgresql.log: Permission denied`

**Describe the results you expected:**

The containers start up and replicate as usual.

**Additional information you deem important (e.g. issue happens only occasionally):**

I debugged the issue quite far and was able to get past all the permission errors. Eventually I reached a point where, on all non-primary nodes, `repmgr_initialize` would silently return before `postgresql_initialize` even fired. I added extensive logging but was not able to solve the problem.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:38 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
lient:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 322
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay store/weaveworks/net-plugin:latest_release
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 5i0zugxsl335bbcry1xii9n3q
  Is Manager: true
  ClusterID: pdr8cv2802s8drzlskvmg2arv
  Managers: 2
  Nodes: 4
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.29.44.101
  Manager Addresses:
   172.29.44.101:2377
   172.29.44.102:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.606GiB
 Name: jhb1
 ID: SBRG:UAKG:OF3R:RFPJ:QLZB:5VOL:UDRK:HIJL:OKHK:3ANB:DUDM:HWKV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: Running Swarm in a two-manager configuration. This configuration provides
         no fault tolerance, and poses a high risk to lose control over the cluster.
         Refer to https://docs.docker.com/engine/swarm/admin_guide/ to configure the
         Swarm for fault-tolerance.

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @hedleyroos 

Thanks so much for reporting this issue! 

I was able to reproduce it, and I will proceed to create an internal task to investigate and fix the permissions issue so te image can be run as "root" as other images.

**Comment by elotrofausto** [comment]
Is there any update on this one?
I can see a more specific error if I flag BITNAMI_DEBUG as True:

postgresql-repmgr 11:56:45.09 INFO  ==> Cloning data from primary node...
repmgr: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that owns the data directory.

Is there any workaround for this? I'm facing an issue where the non-root user runs out of file descriptors, so I need to run the image as root.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but no update yet.
  Could you increase the maximum open files for that user ? Maybe you can use [this](https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/) as reference.
