### ISSUE TITLE
repmgr cannot use custom config file => merge configMap and default

### ISSUE THREAD

**Issue by lerminou** [bitnami/bitnami-docker-postgresql-repmgr#77]
**Description**

I'm using the bitnami postgresql-ha helm chart for kubernetes:

I can't use a custom repmgr file 

https://github.com/bitnami/charts/blob/b8d49647ddff31ab0b7c6e6a8fce6c8d4e8ad2df/bitnami/postgresql-ha/values.yaml#L465

I would like to set a manual failover on my cluster or modify the ssh_options parameters.
Actually, If i set a repmgr I need to override the whoe file but how I can use the actual variable replacement ? 

I don't want to hardcode  the name or id or any other parameters because they need to be unique per pod
node_id=$(repmgr_get_node_id)
node_name='${REPMGR_NODE_NAME}'
 [...]

https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/f95d9ef4d93bc73066daef770cb4c3526c641189/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L447

**Describe the results you received:**
only the repmgr key I set in my values.yml file are used and the pod crash because the configuration is incorrect

**Describe the results you expected:**
I want a merge with the actual defaults

**Comment by Mauraza** [comment]
Hi @lerminou,

> Actually, If i set a repmgr I need to override the whoe file but how I can use the actual variable replacement ?

yes, the value `repmgrConfiguration`  will be the content of `repmgr.conf`.

The documentation of repmgr is https://repmgr.org/docs/repmgr.html#CONFIGURATION-FILE, I don't find anything like your comments.

If you want you can create a PR with the changes you want to include, we will be happy to check it.

**Comment by lerminou** [comment]
@Mauraza , I just created a PR with a working change

If this change seems good for you I will apply the same modification to all supported versions (9/10/11/12/13)

The drawback is the BC break for actual running containers, if a key not overrided is present on the default config, it will be loaded

**Comment by Mauraza** [comment]
Hi @lerminou,

Thanks for the PR!, we will review it!
