### ISSUE TITLE
latest tag

### ISSUE THREAD

**Issue by maxisam** [bitnami/bitnami-docker-postgresql-repmgr#79]
Is there any reason latest tag points to v11 instead of v13?

**Comment by alvneiayu** [comment]
hi @maxisam

When we have several branches in the same product, we keep the latest tag in the version that we think that it is more stable (tested more time, etc). Just to be conservatives. [Here](https://github.com/bitnami/bitnami-docker-postgresql-repmgr#supported-tags-and-respective-dockerfile-links), you can find more information about it.

Let me know if I can help you with something else.

Thanks a lot

Álvaro
