### ISSUE TITLE
Are envs only options to configure?

### ISSUE THREAD

**Issue by smlee729** [bitnami/bitnami-docker-postgresql-repmgr#8]
Hi,

For now it requires env variables like `NODE_PARTNERS`, 
but in Kubernetes setup, we cannot know that info before we deploy it.
So is there any way to feed those env vars from files?

**Comment by juan131** [comment]
Hi @smlee729 

The only parameters that can be consumed from files are passwords (for security reasons) as you can find in the link below:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr#setting-the-root-and-repmgr-passwords-on-first-run

We create a Helm chart that uses this container to deploy PostgreSQL in K8s: https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha

This chart has the ability to automatically set this environment variables (such as the partners nodes) as you can find in the link below:

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L111

**Comment by smlee729** [comment]
Got it thanks!
