### ISSUE TITLE
Starting standby after failover is doing a full clone

### ISSUE THREAD

**Issue by TamarNR** [bitnami/bitnami-docker-postgresql-repmgr#82]
I am wondering if this is the expected behaviour - here are the steps and outcomes:
Stop the Primary container - the standby becomes a Primary in a second or so.
Start the failed Primary - it comesup as a standby after quite a long time (for 9 GB of data).
The log shows that the time is spent on :
`==> Cloning data from primary node...
`

Is it that a full clone is done every time I start a failed standby?

Thanks

[octopus-postgres-rnd-mekorot-65.zip](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/files/6847948/octopus-postgres-rnd-mekorot-65.zip)

**Comment by alemorcuq** [comment]
Yes. This is the code that is executed everytime: https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/245647338bdb60f7130cb6b7b97f9862e8a57794/13/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L530

As you can see, it is doing `repmgr standby clone --fast-checkpoint`

**Comment by TamarNR** [comment]
mmm... have a 120 GB db, that takes a few hours.. thought pg_rewind can be used.

Thanks any way.

**Comment by alemorcuq** [comment]
I have created an internal task to investigate if we can use `pg_rewind` or something similar to speed up the process. Thanks for reporting it, @TamarNR.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a  new revision of the chart with experimental pg_rewind support. Feel free to try and provide feedback :)

**Comment by foarsitter** [comment]
Can't get `pg_rewind` to work in a swarm cluster with the `12.10.0-debian-10-r37` tag. 
```
postgresql-repmgr 16:07:21.88 ,
postgresql-repmgr 16:07:21.89 Welcome to the Bitnami postgresql-repmgr container,
postgresql-repmgr 16:07:21.89 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr,
postgresql-repmgr 16:07:21.89 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues,
postgresql-repmgr 16:07:21.89 ,
postgresql-repmgr 16:07:21.90 DEBUG ==> Configuring libnss_wrapper...,
postgresql-repmgr 16:07:21.92 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **,
postgresql-repmgr 16:07:21.95 INFO  ==> Validating settings in REPMGR_* env vars...,
postgresql-repmgr 16:07:21.96 INFO  ==> Validating settings in POSTGRESQL_* env vars..,
postgresql-repmgr 16:07:21.96 INFO  ==> Querying all partner nodes for common upstream node...,
postgresql-repmgr 16:07:21.98 DEBUG ==> Checking node 'pg-0:5432'...,
postgresql-repmgr 16:07:22.00 DEBUG ==> Skipping: failed to get primary from the node 'pg-0:5432'!,
postgresql-repmgr 16:07:22.01 DEBUG ==> Checking node 'pg-1:5432'...,
postgresql-repmgr 16:07:22.05 DEBUG ==> Pretending primary role node - 'pg-1:5432',
postgresql-repmgr 16:07:22.06 DEBUG ==> Pretending primary set to 'pg-1:5432'!,
postgresql-repmgr 16:07:22.06 INFO  ==> Auto-detected primary node: 'pg-1:5432',
postgresql-repmgr 16:07:22.06 DEBUG ==> Primary node: 'pg-1:5432',
postgresql-repmgr 16:07:22.07 INFO  ==> Preparing PostgreSQL configuration...,
postgresql-repmgr 16:07:22.08 DEBUG ==> Injecting a new postgresql.conf file...,
postgresql-repmgr 16:07:22.08 INFO  ==> postgresql.conf file not detected. Generating it...,
postgresql-repmgr 16:07:22.18 DEBUG ==> Injecting a new pg_hba.conf file...,
postgresql-repmgr 16:07:22.18 INFO  ==> Preparing repmgr configuration...,
postgresql-repmgr 16:07:22.20 DEBUG ==> Node ID: '1000', Rol: 'standby', Primary Node: 'pg-1:5432',
postgresql-repmgr 16:07:22.20 INFO  ==> Initializing Repmgr...,
postgresql-repmgr 16:07:22.21 INFO  ==> Waiting for primary node...,
postgresql-repmgr 16:07:22.21 DEBUG ==> Wait for schema repmgr.repmgr on 'pg-1:5432', will try 6 times with 10 delay seconds (TIMEOUT=60),
postgresql-repmgr 16:07:22.24 DEBUG ==> Schema repmgr.repmgr exists!,
postgresql-repmgr 16:07:22.24 INFO  ==> Rejoining node...,
postgresql-repmgr 16:07:22.26 INFO  ==> Using pg_rewind to primary node...,
postgresql-repmgr 16:07:22.26 INFO  ==> Running pg_rewind data to primary node...,
pg_rewind: fatal: target server must be shut down cleanly,
postgresql-repmgr 16:07:22.28 WARN  ==> pg_rewind failed, resorting to data cloning,
postgresql-repmgr 16:07:22.29 INFO  ==> Cloning data from primary node...,
```

Does this mean that postgres is already running inside the pg-0 container?

**Comment by javsalgar** [comment]
Hi,

It seems that in this case the PostgreSQL instance did not shut down correctly and pg_rewind is unable to make it work. As an experimental feature, right now it only attempts to execute pg_rewind and if it doesn't work as expected then resort to the basic command.

In this case, if you want to execute pg_rewind, my advice would be to launch the chart in diagnostic mode `diagnosticMode.enabled=true`, enter the affected container fix the not shut down cleanly issue (I think by starting and stopping PostgreSQL) should be enough, and then re-deploy to see if the pg_rewind command works as expected.

**Comment by foarsitter** [comment]
Thanks for your quick response! After some trail and error I got it working with the following modification of `repmgr_pgrewind()` but I miss the bigger picture. 

```sh
repmgr_pgrewind() {

    info "Running pg_rewind data to primary node..."
  
    REPMGR_USE_PGREWIND="no"
  
    postgresql_initialize
    postgresql_start_bg "false"
    info "Stopping PostgreSQL..."
    local -r -a cmd=("pg_ctl" "stop" "-w" "-D" "$POSTGRESQL_DATA_DIR" "-m" "$POSTGRESQL_SHUTDOWN_MODE" "-t" "$POSTGRESQL_PGCTLTIMEOUT")
    if am_i_root; then
      gosu "$POSTGRESQL_DAEMON_USER" "${cmd[@]}"
    else
      "${cmd[@]}"
    fi
  
    REPMGR_USE_PGREWIND="yes"

    info "Running pg_rewind data to primary node..."
    local -r flags=("-D" "$POSTGRESQL_DATA_DIR" "--source-server" "host=${REPMGR_CURRENT_PRIMARY_HOST} port=${REPMGR_CURRENT_PRIMARY_PORT} user=${REPMGR_USERNAME} dbname=${REPMGR_DATABASE}")

    if [[ "$REPMGR_USE_PASSFILE" = "true" ]]; then
        PGPASSFILE="$REPMGR_PASSFILE_PATH" debug_execute "${POSTGRESQL_BIN_DIR}/pg_rewind" "${flags[@]}"
    else
        PGPASSWORD="$REPMGR_PASSWORD" debug_execute "${POSTGRESQL_BIN_DIR}/pg_rewind" "${flags[@]}"
    fi
}
```

```
postgresql-repmgr 12:04:26.41 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 12:04:27.07 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 12:04:27.48 INFO  ==> Running pg_rewind data to primary node...
pg_rewind: source and target cluster are on the same timeline
pg_rewind: no rewind required
postgresql-repmgr 12:04:27.50 INFO  ==> Initializing PostgreSQL database...
```

**Comment by foarsitter** [comment]
Is this the correct place to provide feedback for the pg_rewind feature? Postgresql 13 tries to stop cleanly with the postgres `--single` flag, but this flag is not supported in replication mode. Therefore the pg_rewind `--no-ensure-shutdown` flag is needed.

**Comment by rafariossaa** [comment]
> Is this the correct place to provide feedback for the pg_rewind feature?

I think we can follow this in your PR.
