### ISSUE TITLE
repmgr witness node

### ISSUE THREAD

**Issue by warmanton** [bitnami/bitnami-docker-postgresql-repmgr#85]
**Description**

Is an instructions how to set up witness node ? I hope witness node will prevent split brain scenario below.

**Steps to reproduce the issue:**

1. Create repmgr cluster
2. Do network isolation of master node (iptables -A INPUT -s <ip of first slave> -j DROP ; iptables -A INPUT -s <ip of second slave> -j DROP ; )
3. Wait for 1-2 minutes and remove network isolation
4. Check rempgr status - should show two primary nodes

**Comment by rafariossaa** [comment]
Hi,
  Not very sure what you mean by "witness node", could you provide more background ?
  In any case if you add more nodes and you do a similar isolation you will end in the same scenario.

**Comment by warmanton** [comment]
> Hi,
> Not very sure what you mean by "witness node", could you provide more background ?
> In any case if you add more nodes and you do a similar isolation you will end in the same scenario.

Hi.
https://repmgr.org/docs/4.2/using-witness-server.html

In short: if two secondaries see failed primary and see alive witness then slaves begin to do election of new primary. If secondaries see failed primary and failed witness at the same time then they think that they are disconnected from the world and do nothing but waiting for connection to the primary or to the witness or to the both.

I know if I will do some isolation of primary and witness then I will get the same result some how but witness node is a point to make decision for secondaries "to elect new master or not". Assuming that primary and witness cannot fail at the same time :-). Witness should be on different hardware node then any other repmgr component.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the info.
  In this case, and answering your initial question: `Is an instructions how to set up witness node ? ` there are not instructions to provide a witness node. The current initialization logic of the container is not ready for this scenario, it is needed to run other repmgr commands. Have into account that these container are designed to be used mainly in kubernetes scenarios and having a witness node is a quite particular case in this scenario.
