### ISSUE TITLE
Best practice to run in PSP

### ISSUE THREAD

**Issue by horiee** [bitnami/bitnami-docker-postgresql-repmgr#87]
**Description**
How run this image agains stricly configured kubernetes clusters. Is there some sort of recomendations or examples ?
I was following bitnami/bitnami-docker-nginx#139 to fix issue with /tmp dir being read-only file system but there are other issues as well. 
Basically it's all about this rule - **applications cannot write files into the docker file system**.
If i mount empty dir sometimes it overwrites folder which is expected to have some files thus it's a no go.
Has anyone been solving this before?

Raised the same issue with pgpool https://github.com/bitnami/bitnami-docker-pgpool/issues/60

```
postgresql-repmgr 10:38:18.60 
postgresql-repmgr 10:38:18.60 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 10:38:18.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 10:38:18.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 10:38:18.61 
postgresql-repmgr 10:38:18.61 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 10:38:18.64 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 10:38:18.64 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 10:38:18.65 INFO  ==> Querying all partner nodes for common upstream node...
...
postgresql-repmgr 10:38:18.72 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 10:38:18.72 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 10:38:18.73 DEBUG ==> User injected custom configuration detected!
postgresql-repmgr 10:38:18.73 DEBUG ==> Injecting a new pg_hba.conf file...
postgresql-repmgr 10:38:18.74 INFO  ==> Preparing repmgr configuration...
/opt/bitnami/scripts/librepmgr.sh: line 450: /opt/bitnami/repmgr/conf/repmgr.conf.tmp: Read-only file system
```

**Comment by juan131** [comment]
Hi @horiee 

This is image is not designed to run on a read-only filesystem. We designed it to write all the data under the `/bitnami/postgresql` directory as it's explained in the link below:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr#persisting-your-application

However, we cannot guarantee that other write operations will be done during the container initialization on different paths of the filesystem. 

We do understand that "read-only" filesystems is a great way to enhance the security in your apps, but please not it's not the unique one. There are many other less restrictive actions you can apply such as using a SecurityContext to ensure the container and volumes use a non-root user, configuring network policies to control what traffic can access your apps, or using PodSecurityPolicies to limit privilege escalation and network capabilities.
