### ISSUE TITLE
Add distinct WAL directory support

### ISSUE THREAD

**Issue by davoustp** [bitnami/bitnami-docker-postgresql-repmgr#89]
**Description**

Deploying a Postgres cluster for performance usually entails using separate disks for data and WAL files (usually using a more costly but faster disk such as SSD drives for WAL files). This translates into distinct persistent volumes with different storage classes in Kubernetes.

This can be easily achieved by setting environment variable `POSTGRESQL_INITDB_WAL_DIR` to point to a bind-mounted persistent volume.

However, this fails during replication from the primary node for two reasons :
1. the `pg_basebackup`command issued to clone or rewind from the master does not include the `--waldir $POSTGRESQL_INITDB_WAL_DIR` option
2. when this option is specified, then the specified directory *must be empty* as specified in https://www.postgresql.org/docs/13/app-pgbasebackup.html :
> As with the main target directory, waldir need not exist already, but if it does exist it must be empty.

Item 1) above can be worked around by specifying a `repmgr.conf` file with the appropriate `pg_basebackup_options` entry.

But 2) cannot be worked around: cleaning up the WAL directory must be performed *only and only when* performing this clone / rewind operation, which requires changing the `librepmgr.sh`script (more specifically, functions `repmgr_clone_primary()` and `repmgr_rewind()`)

**Steps to reproduce the issue:**

1. Start a 2-node cluster with environment variable `POSTGRESQL_INITDB_WAL_DIR` set to a separate directory
2. Wait for cluster creation
3. Restart the standby node
4. Wait for standby resync
5. Check the location of the WAL files: `ls -alh /bitnami/postgresql/data/pg_wal`

**Describe the results you received:**

The `/bitnami/postgresql/data/pg_wal` is a plain directory.

**Describe the results you expected:**

The `/bitnami/postgresql/data/pg_wal` should be a symbolic link to the directory specified in `POSTGRESQL_INITDB_WAL_DIR`.

**Version**

Reproduced against `bitnami/postgresql-repmgr:13.4.0-debian-10-r24`

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Performed using Google Cloud Platform

**Comment by carrodher** [comment]
Thanks for the detailed information! I'm not totally sure what is the best way to ensure that this use case is 100% covered; since the logic is bashed on bash and publicly available in this repo and if you have any hint or code, we will be happy to review any PR if you want to contribute!

**Comment by davoustp** [comment]
Sure, this should be simple enough. I'll find a proper way to validate this code change before a PR submission.

**Comment by davoustp** [comment]
Not sure that the submitted PR generates a notification to you guys... Here it is. 🙂

**Comment by Mauraza** [comment]
Hi @davoustp,

Thanks for the contribution! We will review!
