### ISSUE TITLE
Do you have plans to release a version that supports IMCS (In-Memory Columnar Store) in the future?

### ISSUE THREAD

**Issue by joocfresh** [bitnami/bitnami-docker-postgresql-repmgr#92]
**Description**

It works well. I hope this will also support IMCS.

**Comment by carrodher** [comment]
Thanks for the suggestion, we are not used to including this kind of module by default in the image unless we see a lot of traction from the community. It is difficult to find a balance between support different third-party modules or plugins and maintain the image light or simple from a configuration point of view.

As the code is present in this repository, feel free to customize the image to meet your requirements
