### ISSUE TITLE
changing permissions of '/bitnami/postgresql/data': Operation not permitted and standby container data is cleared

### ISSUE THREAD

**Issue by joylili** [bitnami/bitnami-docker-postgresql-repmgr#94]
**Description**

I have two problems：
1、When I start docker container with -v /bitnami/postgresql/data:/bitnami/postgresql/data,I don't start container.
2、When I start docker container without -v,I can start container,but standby node container'data is cleared and reinitialized.
I want mount container's data to host,and when I restart standby node container,do not clear data.Because when I start standby node container,and  if the primary host is down,then datadir is cleared,I'm afraid the data is lost and can't be found.

**Steps to reproduce the issue:**

docker run -d --name pg-0\
  --network host \
  --env REPMGR_PARTNER_NODES=pg-0,pg-1 \
  --env REPMGR_NODE_NAME=pg-0 \
  --env REPMGR_NODE_NETWORK_NAME=pg-0 \
  --env REPMGR_PRIMARY_HOST=pg-0 \
  --env REPMGR_PASSWORD=repmgrpass \
  --env POSTGRESQL_POSTGRES_PASSWORD=adminpassword \
  --env POSTGRESQL_USERNAME=customuser \
  --env POSTGRESQL_PASSWORD=custompassword \
  --env POSTGRESQL_DATABASE=customdatabase \
 -v /bitnami/postgresql/data:/bitnami/postgresql/data \
postgresql-repmgr:10.18.0

**Describe the results you received:**

docker container do not start,but received "Exited".

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```Docker version 19.03.13
(paste your output here)
```
postgresql-repmgr 08:11:25.80 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
hostname: Temporary failure in name resolution
postgresql-repmgr 08:11:25.85 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 08:11:25.85 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 08:11:25.86 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 08:11:25.88 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 08:11:25.89 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 08:11:25.90 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 08:11:26.01 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 08:11:26.03 INFO  ==> Initializing Repmgr...
postgresql-repmgr 08:11:26.03 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 08:11:26.04 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 08:11:26.04 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql-repmgr 08:11:26.06 WARN  ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
So, about the second issue, you mentioned that the volumes get cleared when you start without `-v`, so there are no bound volumes. Could you explain the reason for starting the secondary node without volumes? The fact that it gets cleared is expected in the sense that there is no persistence attached.

**Comment by joylili** [comment]
Thank you for your reply.I start docker container with -v volume. I looked into startup scripts  last two days,I found there is “rm -rf” code in repmgr_rewind method from librepmgr.sh, so I know why the data dir files was cleared and then reinitialized.What I don't understand is why not use pg_rewind command？I don't want to delete all the data  when I restart standby host.What should I do?

**Comment by javsalgar** [comment]
Hi,

We would need to evaluate the effects of changing that `rm -rf` with a `pg_rewind` command. Do you have experience with this command? Did you try changing it with, for example a small fork? That would give us clues about the effects and maybe change it with a PR
