### ISSUE TITLE
Unable to set max_wal_size via custom postgresql.conf file

### ISSUE THREAD

**Issue by ynleborg** [bitnami/bitnami-docker-postgresql-repmgr#95]
I have a custom postgresql.conf file with max_wal_size set to 1024MB. 
It is properly handled in libpostgresql.sh:
```is_boolean_yes "$create_conf_file" && postgresql_configure_replication_parameters```

but later in librepmgr.sh there is unconditional call to

```postgresql_configure_replication_parameters```

which reverts max_wal_size to 400MB

Why this is implemented that way? How can I override this value?

**Comment by juan131** [comment]
Hi @ynleborg 

On question: are you mounting your custom **postgresql.conf** as described in [this section of the README.md](https://github.com/bitnami/bitnami-docker-postgresql-repmgr#configuration-file)?

**Comment by ynleborg** [comment]
@juan131 
Yes, exactly that way.

**Comment by juan131** [comment]
Yes... I can reproduce the issue. You're 100%, it seems we're not taking int account in `librepmgr.sh` that PostgreSQL configuration file could've been mounted with a custom configuration. Let me work on a PR to address this.

**Comment by juan131** [comment]
New releases adding the fix were release, see the commits below:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/commit/61a884770e7ebfe5ec0aa7b6f8128e632a60ec63
- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/commit/61198a4dbdebf61373cdf8f2d603dd1575cc04f8
- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/commit/b829607283f0e69829293977a01f77d3df169878
- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/commit/49c13cc888bfa23e33cd68d1823a5a45e9a17d33
- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/commit/ad29293ee45f3caffbbe3ee7057d2b89511f91bc

Could you please give a try to the new containers @ynleborg ?
