### ISSUE TITLE
pg in nomad

### ISSUE THREAD

**Issue by Parthi10** [bitnami/bitnami-docker-postgresql-repmgr#97]
I'm integrating pg replication in nomad, while running the job file I'm getting the following error.

ERROR:
```
postgresql-repmgr 14:43:05.33 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 14:43:05.39 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 14:43:05.39 ERROR ==> The node name does not follow the required format. Valid format: ^.*+-[0-9]+$
```

**Comment by carrodher** [comment]
This error is reported by a validation done checking the node name:
```bash
    if [[ -z "$REPMGR_NODE_NAME" ]]; then
        print_validation_error "The node name is required. Set the environment variable REPMGR_NODE_NAME with the node name."
    elif [[ ! "$REPMGR_NODE_NAME" =~ ^.*+-[0-9]+$ ]]; then
        print_validation_error "The node name does not follow the required format. Valid format: ^.*+-[0-9]+$"
    fi
```

You should adapt `REPMGR_NODE_NAME` to match the proper format.

**Comment by Parthi10** [comment]
yes, thanks @carrodher.

**Comment by Parthi10** [comment]
@carrodher,  i'm integrating postgres-replication in nomad, but the primary and replication nodes are not communicating, after 60sec replication container failing.
Here is my job config,

job "job" {
  datacenters = ["dc1"]
  type        = "service"

  group "group" {

    count = 1

    network {
      mode = "host"
      port "db" {
        static = 20555
        to     = 5432
      }
      port "db1" {
        static = 29052
        to     = 5432
      }
    }

    task "master" {
      kill_timeout = "120s"
      driver       = "docker"
      config {
        image = "bitnami/postgresql-repmgr:latest"
        ports = ["db"]
      }
      env {
        POSTGRESQL_POSTGRES_PASSWORD = "adminpassword"
        POSTGRESQL_USERNAME          = "customuser"
        POSTGRESQL_PASSWORD          = "custompassword"
        POSTGRESQL_DATABASE          = "customdatabase"
        REPMGR_PASSWORD              = "repmgrpassword"
        REPMGR_PRIMARY_HOST          = "master-${NOMAD_ALLOC_ID}"
        REPMGR_PRIMARY_PORT          = "5432"
        REPMGR_PARTNER_NODES         = "naster-${NOMAD_ALLOC_ID}, slave-${NOMAD_ALLOC_ID}:5432"
        REPMGR_NODE_NAME             = "master-${NOMAD_ALLOC_ID}"
        REPMGR_NODE_NETWORK_NAME     = "master-${NOMAD_ALLOC_ID}"
        REPMGR_PORT_NUMBER           = "5432"
        REPMGR_NODE_ID               = "master-${NOMAD_ALLOC_ID}"
      }
      resources {
        memory = 256
      }
    }

    task "slave" {
      driver       = "docker"
      kill_timeout = "120s"
      config {
        image = "bitnami/postgresql-repmgr:latest"
        ports = ["db1"]
      }
      env {
        POSTGRESQL_POSTGRES_PASSWORD  = "adminpassword"
        POSTGRESQL_USERNAME           = "customuser"
        POSTGRESQL_PASSWORD           = "custompassword"
        POSTGRESQL_DATABASE           = "customdatabase"
        REPMGR_PASSWORD               = "repmgrpassword"
        REPMGR_PRIMARY_HOST           = "master-${NOMAD_ALLOC_ID}"
        REPMGR_PRIMARY_PORT           = "5432"
        REPMGR_PARTNER_NODES          = "master-${NOMAD_ALLOC_ID}, slave-${NOMAD_ALLOC_ID}:5432"
        REPMGR_NODE_NAME              = "slave-${NOMAD_ALLOC_ID}"
        REPMGR_NODE_NETWORK_NAME      = "slave-${NOMAD_ALLOC_ID}"
        REPMGR_PORT_NUMBER            = "5432"
        REPMGR_NODE_ID                = "master-${NOMAD_ALLOC_ID}"
      }
      resources {
        memory = 128
      }
    }
  }
}

**Comment by carrodher** [comment]
Unfortunately, nomad is not something tested by us so it is difficult to reproduce the same scenario on our side. Can you try to replicate the same configuration but using a docker-compose?

**Comment by Parthi10** [comment]
yes, in docker-compose it's working fine @carrodher.

**Comment by carrodher** [comment]
Maybe then it's an issue with nomad itself or how the configuration is "migrated" from docker-compose to nomad... I'm not sure how can we help with this topic

**Comment by Parthi10** [comment]
@carrodher, thanks, I'll look into nomad configuration.
