### ISSUE TITLE
Repmgrd can't start if I add a custom postgresql.conf on a specific server

### ISSUE THREAD

**Issue by dennissehalic** [bitnami/bitnami-docker-postgresql-repmgr#99]
Hello

I'm getting a weird error where everything works fine on one server (Centos 8.5), but not the other (Redhat 8.5). If I mount a custom postgresql.conf, repmgrd fails to start regardless of which config is in the file. I can mount custom pg_hba.conf and repmgr.conf on both servers, but a custom postgresql.conf just breaks on one but not the other. I've re-built the container with BITNAMI_DEBUG and xtrace enabled everywhere.

**Server that doesn't work**
podman version 3.3.1
Linux tz1pql01t.corpnet.teracom.se 4.18.0-348.el8.x86_64 #1 SMP Mon Oct 4 12:17:22 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux release 8.5 (Ootpa)

**Server that does work**
podman version 3.3.1
Linux localhost.localdomain 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 8.5.2111

{
    "gosu": {
        "arch": "amd64",
        "digest": "3e6fc37ca073b10a73a804d39c2f0c028947a1a596382a4f8ebe43dfbaa3a25e",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "1.14.0-0"
    },
    "postgresql-repmgr": {
        "arch": "amd64",
        "digest": "04d8208b3ffe96f7aaf22f30d940b2c6543d6c41a31c00575e62fb13a6e1e383",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "12.9.0-0"
    }
}

**Run command:**
```
podman run -d --name repmgr-postgres-test -p 5432:5432  --env-file /home/repmgr/test_env.sh --userns=keep-id -v "/home/repmgr/test/:/bitnami/postgresql:Z" -v "/home/repmgr/test-pgconf:/bitnami/repmgr/conf:Z" -v "/home/repmgr/pghost:/opt/barman/pghost:Z" localhost/repmgr-xinetd-postgres-12.9.0 && podman logs -f repmgr-postgres-test && podman logs -f repmgr-postgres-test
```

**Log output on the server that works**
```
postgresql-repmgr 13:05:58.87 INFO  ==> ** Starting repmgrd **
+ am_i_root
++ id -u
+ [[ 1001 = \0 ]]
+ false
+ exec /opt/bitnami/repmgr/bin/repmgrd --pid-file=/opt/bitnami/repmgr/tmp/repmgr.pid -f /opt/bitnami/repmgr/conf/repmgr.conf --daemonize=false
[2021-11-22 13:05:58] [NOTICE] repmgrd (repmgrd 5.3) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-11-22 13:05:58] [NOTICE] starting monitoring of node "pg-0" (ID: 1000)
[2021-11-22 13:05:58] [NOTICE] monitoring cluster primary "pg-0" (ID: 1000)
```

**Log output on the server that doesn't work**
```
+ info 'Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected'
+ log '\033[38;5;2mINFO \033[0m ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected'
... (LOTS! of logs)...
2021-11-22 13:46:39.629 GMT [103] LOG:  redo done at 0/3000430
2021-11-22 13:46:39.638 GMT [101] LOG:  database system is ready to accept connections
 done
server started
+ pg_isready_args=("-U" "postgres")
+ local pg_isready_args
+ local counter=60
+ /opt/bitnami/postgresql/bin/pg_isready -U postgres
+ info '** Starting repmgrd **'
+ log '\033[38;5;2mINFO \033[0m ==> ** Starting repmgrd **'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6mpostgresql-repmgr \033[38;5;5m13:46:39.68 \033[0m\033[38;5;2mINFO \033[0m ==> ** Starting repmgrd **'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6mpostgresql-repmgr \033[38;5;5m13:46:39.68 \033[0m\033[38;5;2mINFO \033[0m ==> ** Starting repmgrd **'
postgresql-repmgr 13:46:39.68 INFO  ==> ** Starting repmgrd **
+ am_i_root
++ id -u
+ [[ 1001 = \0 ]]
+ false
+ exec /opt/bitnami/repmgr/bin/repmgrd --pid-file=/opt/bitnami/repmgr/tmp/repmgr.pid -f /opt/bitnami/repmgr/conf/repmgr.conf --daemonize=false
[2021-11-22 13:46:39] [NOTICE] repmgrd (repmgrd 5.3) starting up
[2021-11-22 13:46:39] [ERROR] connection to database failed
[2021-11-22 13:46:39] [DETAIL]
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[2021-11-22 13:46:39] [DETAIL] attempted to connect using:
  user=repmgr password=repmgrpass connect_timeout=5 dbname=repmgr host=172.21.8.129 port=5433 fallback_application_name=repmgr options=-csearch_path=
```

If I stop the broken container, remove postgresql.conf from the mounted directory it starts just fine and it doesn't matter if I keep the custom pga_hba.conf and/or repmgr.conf files. So repmgr thinks it can't connect to the postgres-server even though postgres has started as it should and the only difference is that a custom postgresql.conf either exists or doesn't exist. I even tested to use the exact template config that the container creates for itself when no custom config exists.

Any ideas?

**Comment by migruiz4** [comment]
Hi @dennissehalic,

The error message says that repmgr is failing to connect with PostgreSQL.

The connection string is shown below, so I would recommend to :
```
user=repmgr password=repmgrpass connect_timeout=5 dbname=repmgr host=172.21.8.129 port=5433 fallback_application_name=repmgr options=-csearch_path= 
```

There, I see two settings that differ from default: `port=5433` (default port is 5432), and `options=-csearch_path=`.

If those two settings are being included in your custom `repmgr.conf`, I would recommend removing them and trying to restart repmgr in case they are the cause of the problem.

You could also try to mount a config file having the exact same content as the one generated by the container. That would also help discard misconfiguration issues.

**Comment by dennissehalic** [comment]
Reason some logs are with port 5433 is because I've been trying different container versions and with xtrace etc and instead of removing old test containers, I've added new ones but with different outside ports, they have still been forwarded to 5432 inside the containers. Same thing with repmgr.conf.

Like I said in the end, I've tried copying exact config file the container generates.

But here are some more logs:

**Create a new container without mounting any files in pgconf/ and see that it starts like it should**
```
[repmgr@host ~]$ podman run -d --name test  --userns=keep-id -p 5432:5432   -v "/home/repmgr/test:/bitnami/postgresql:Z"   -v "/home/repmgr/pgconf:/bitnami/repmgr/conf:Z"   --env REPMGR_NODE_NAME=pg-0   --env REPMGR_PRIMARY_HOST=172.21.8.128   --env REPMGR_PRIMARY_PORT=5432   --env REPMGR_PARTNER_NODES=172.21.8.128:5432   --env REPMGR_NODE_NETWORK_NAME=172.21.8.128   --env REPMGR_PASSWORD=repmgrpass   --env POSTGRESQL_PASSWORD=secretpass   --env BITNAMI_DEBUG=true   repmgr-xinetd-postgres && podman logs -f test
e2cd4e37f19aa5a53c9e421a2bb3a0d619c71623716e5597a8ff0e5e2231e776
postgresql-repmgr 11:32:35.05
postgresql-repmgr 11:32:35.06 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 11:32:35.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 11:32:35.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 11:32:35.07
postgresql-repmgr 11:32:35.25 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
...
postgresql-repmgr 11:32:42.68 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-11-23 11:32:42.721 GMT [265] LOG:  pgaudit extension initialized
2021-11-23 11:32:42.721 GMT [265] LOG:  starting PostgreSQL 12.9 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-11-23 11:32:42.722 GMT [265] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-11-23 11:32:42.722 GMT [265] LOG:  listening on IPv6 address "::", port 5432
2021-11-23 11:32:42.724 GMT [265] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-11-23 11:32:42.732 GMT [265] LOG:  redirecting log output to logging collector process
2021-11-23 11:32:42.732 GMT [265] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-11-23 11:32:42.735 GMT [267] LOG:  database system was shut down at 2021-11-23 11:32:42 GMT
2021-11-23 11:32:42.739 GMT [265] LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 11:32:42.82 INFO  ==> ** Starting repmgrd **
[2021-11-23 11:32:42] [NOTICE] repmgrd (repmgrd 5.3) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-11-23 11:32:42] [NOTICE] starting monitoring of node "pg-0" (ID: 1000)
[2021-11-23 11:32:42] [NOTICE] monitoring cluster primary "pg-0" (ID: 1000)
```

**Check cluster status**
```
[repmgr@host ~]$ podman exec test repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
 ID   | Name | Role    | Status    | Upstream | Location | Priority | Timeline | Connection string
------+------+---------+-----------+----------+----------+----------+----------+---------------------------------------------------------------------------------------------
 1000 | pg-0 | primary | * running |          | default  | 100      | 1        | user=repmgr password=repmgrpass host=172.21.8.128 dbname=repmgr port=5432 connect_timeout=5
```



**Copy the generated configuration file to mount dir and start the container again**
[repmgr@host ~]$ podman stop test
[repmgr@host ~]$ cp /home/repmgr/test/conf/postgresql.conf /home/repmgr/pgconf/
[repmgr@host ~]$ podman start test && podman logs -f --since 5m test
test
[2021-11-23 11:33:24] [NOTICE] TERM signal received
postgresql-repmgr 11:35:09.92
postgresql-repmgr 11:35:09.92 Welcome to the Bitnami postgresql-repmgr container
...
postgresql-repmgr 11:38:17.68 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-11-23 11:38:17.742 GMT [100] LOG:  pgaudit extension initialized
2021-11-23 11:38:17.742 GMT [100] LOG:  starting PostgreSQL 12.9 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-11-23 11:38:17.743 GMT [100] LOG:  listening on IPv6 address "::1", port 5432
2021-11-23 11:38:17.744 GMT [100] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-11-23 11:38:17.747 GMT [100] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-11-23 11:38:17.756 GMT [100] LOG:  redirecting log output to logging collector process
2021-11-23 11:38:17.756 GMT [100] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-11-23 11:38:17.759 GMT [102] LOG:  database system was interrupted; last known up at 2021-11-23 11:35:11 GMT
2021-11-23 11:38:17.780 GMT [102] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-23 11:38:17.781 GMT [102] LOG:  redo starts at 0/3000350
2021-11-23 11:38:17.781 GMT [102] LOG:  invalid record length at 0/3000648: wanted 24, got 0
2021-11-23 11:38:17.781 GMT [102] LOG:  redo done at 0/3000620
2021-11-23 11:38:17.791 GMT [100] LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 11:38:17.83 INFO  ==> ** Starting repmgrd **
[2021-11-23 11:38:17] [NOTICE] repmgrd (repmgrd 5.3) starting up
[2021-11-23 11:38:18] [ERROR] connection to database failed
[2021-11-23 11:38:18] [DETAIL]
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[2021-11-23 11:38:18] [DETAIL] attempted to connect using:
  user=repmgr password=repmgrpass connect_timeout=5 dbname=repmgr host=172.21.8.128 port=5432 fallback_application_name=repmgr options=-csearch_path=
```
Now repmgr thinks it can't connect to the postgres server


**Remove the custom config and start the container again**
```
[repmgr@host ~]$ rm pgconf/postgresql.conf
[repmgr@host ~]$ podman start test && podman logs -f --since 5m test
test
postgresql-repmgr 11:38:16.84
postgresql-repmgr 11:38:16.85 Welcome to the Bitnami postgresql-repmgr container
...
2021-11-23 11:41:12.489 GMT [152] LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 11:41:12.53 INFO  ==> ** Starting repmgrd **
[2021-11-23 11:41:12] [NOTICE] repmgrd (repmgrd 5.3) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-11-23 11:41:12] [NOTICE] starting monitoring of node "pg-0" (ID: 1000)
[2021-11-23 11:41:12] [NOTICE] monitoring cluster primary "pg-0" (ID: 1000)
```

It starts just fine

**Check so we can connect both from the host and inside from the container**
[repmgr@host ~]$ psql -h 172.21.8.128 -U repmgr -p 5432
Password for user repmgr:
psql (10.17, server 12.9)
WARNING: psql major version 10, server major version 12.
         Some psql features might not work.
Type "help" for help.

repmgr=#

[repmgr@host ~]$ podman exec -it test /bin/bash
repmgr@e2cd4e37f19a:/$ psql -h 172.21.8.128 -U repmgr -p 5432
Password for user repmgr:
psql (12.9)
Type "help" for help.

repmgr=#

**Comment by migruiz4** [comment]
Hi @dennissehalic,

I'm sorry for the late response. I haven't been able to reproduce your issue, so maybe we can discard some issues if you reproduce these steps:
```bash
# Download the latest docker-compose
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-postgresql-repmgr/master/14/debian-10/docker-compose.yml
# Start the containers using docker-compose
docker-compose up
# Log into the container pg-0
docker-compose exec pg-0 bash
# Copy the default configuration file
docker-compose exec pg-0 cat /opt/bitnami/postgresql/conf/postgresql.conf > postgresql.conf
```

Then, modify the docker-compose to also mount the configuration file:
```diff
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
+      -/local_path/to/postgresql.conf:/opt/bitnami/postgresql/conf/postgresql.conf
    environment:
```
Set proper permissions for the conf file and stop/start container pg-0 again:
```
sudo chmod 644 postgresql.conf 
sudo chown 1001:0 postgresql.conf 
docker-compose kill pg-0
docker-compose up pg-0
```

In my case, container `pg-0` was able to start with no problem.

**Comment by dennissehalic** [comment]
Have to say sorry as well hehe, forgot about this. I'll do some  testing and get back to you next week
